version: "3.9"

networks:
  diligent:
    driver: bridge

services:
  prometheus:
    image: prom/prometheus:v2.36.0
    ports:
      - "9090:9090"
    volumes:
      - ./docker-compose-files/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - diligent

  grafana:
    image: grafana/grafana:8.5.4
    ports:
      - "3000:3000"
    volumes:
      - ./docker-compose-files/grafana/provisioning:/etc/grafana/provisioning
      - ./docker-compose-files/grafana/dashboards:/grafana/dashboards
    networks:
      - diligent

  minion0:
    build:
      context: .
      dockerfile: Minion.Dockerfile
    image: diligent/minion:latest
    command: ["/diligent/minion", "--boss", "boss", "--advertise-addr", "minion0"]
    networks:
      - diligent

  boss:
    build:
      context: .
      dockerfile: Boss.Dockerfile
    image: diligent/boss:latest
    ports:
      - "5710:5710"
    networks:
      - diligent

  shell:
    build:
      context: .
      dockerfile: Shell.Dockerfile
    image: diligent/shell:latest
    command: ["/diligent/shell", "--boss", "boss"]
    stdin_open: true
    tty: true
    networks:
      - diligent

