{
 "title": "Basic Workload",
 "time": { "from": "now-2h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Configuration", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Concurrency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(diligent_config_concurrency)",
     "legendFormat": "Configured Concurrency"
    },
    { "expr": "sum(diligent_concurrency)", "legendFormat": "Actual Concurrency" }
   ]
  },
  {
   "title": "Transactions  Enabled",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "diligent_config_transaction_enabled",
     "legendFormat": "Txn Enabled-{{instance}}"
    }
   ]
  },
  {
   "title": "Batch Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "diligent_config_batch_size",
     "legendFormat": "Configured Batch Size-{{instance}}"
    }
   ]
  },
  {
   "title": "DB Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "diligent_db_connections", "legendFormat": "{{label}}-{{instance}}" }
   ]
  },
  { "title": "Statements", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Statement Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (statement) (diligent_statement_duration_seconds_count)",
     "legendFormat": "{{statement}}"
    }
   ]
  },
  {
   "title": "Statement Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (statement) (rate(diligent_statement_duration_seconds_count[1m]))",
     "legendFormat": "{{statement}}"
    }
   ]
  },
  {
   "title": "Statement Failure Counts",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (statement) (diligent_statement_failure)",
     "legendFormat": "failed {{statement}}s"
    },
    {
     "expr": "sum by (statement) (diligent_statement_affected_rows_mismatch)",
     "legendFormat": "row mismatch {{statement}}s"
    }
   ]
  },
  {
   "title": "Statement Duration p999",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.999, sum by (le, statement) (rate(diligent_statement_duration_seconds_bucket[1m])))",
     "legendFormat": "{{statement}}"
    }
   ]
  },
  {
   "title": "Statement Duration p99",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 19 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le, statement) (rate(diligent_statement_duration_seconds_bucket[1m])))",
     "legendFormat": "{{statement}}"
    }
   ]
  },
  {
   "title": "Statement Duration Mean",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 19 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "(sum by (statement) (rate(diligent_statement_duration_seconds_sum[1m]))) / (sum by (statement) (rate(diligent_statement_duration_seconds_count[1m])))",
     "legendFormat": "{{statement}}"
    }
   ]
  },
  { "title": "Transactions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Transaction Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(diligent_transaction_duration_seconds_count[1m]))",
     "legendFormat": "Transaction Rate"
    }
   ]
  },
  {
   "title": "Transaction Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.999, sum by (le) (rate(diligent_transaction_duration_seconds_bucket[1m])))",
     "legendFormat": "p999"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(diligent_transaction_duration_seconds_bucket[1m])))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(diligent_transaction_duration_seconds_bucket[1m])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.75, sum by (le) (rate(diligent_transaction_duration_seconds_bucket[1m])))",
     "legendFormat": "p75"
    },
    {
     "expr": "histogram_quantile(0.50, sum by (le) (rate(diligent_transaction_duration_seconds_bucket[1m])))",
     "legendFormat": "p50"
    },
    {
     "expr": "(sum (rate(diligent_transaction_duration_seconds_sum[1m]))) / (sum (rate(diligent_transaction_duration_seconds_count[1m])))",
     "legendFormat": "Mean"
    }
   ]
  },
  {
   "title": "Statements Per Transaction by Type",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(diligent_statement_duration_seconds_count{statement=\"begin\"}[1m])) / sum(rate(diligent_transaction_duration_seconds_count[1m]))",
     "legendFormat": "begin/txn"
    },
    {
     "expr": "sum(rate(diligent_statement_duration_seconds_count{statement=\"commit\"}[1m])) / sum(rate(diligent_transaction_duration_seconds_count[1m]))",
     "legendFormat": "commit/txn"
    },
    {
     "expr": "sum(rate(diligent_statement_duration_seconds_count{statement=\"select\"}[1m])) / sum(rate(diligent_transaction_duration_seconds_count[1m]))",
     "legendFormat": "select/txn"
    },
    {
     "expr": "sum(rate(diligent_statement_duration_seconds_count{statement=\"insert\"}[1m])) / sum(rate(diligent_transaction_duration_seconds_count[1m]))",
     "legendFormat": "insert/txn"
    },
    {
     "expr": "sum(rate(diligent_statement_duration_seconds_count{statement=\"update\"}[1m])) / sum(rate(diligent_transaction_duration_seconds_count[1m]))",
     "legendFormat": "update/txn"
    },
    {
     "expr": "sum(rate(diligent_statement_duration_seconds_count{statement=\"delete\"}[1m])) / sum(rate(diligent_transaction_duration_seconds_count[1m]))",
     "legendFormat": "delete/txn"
    },
    {
     "expr": "sum(rate(diligent_statement_duration_seconds_count[1m])) / sum(rate(diligent_transaction_duration_seconds_count[1m]))",
     "legendFormat": "total/txn"
    }
   ]
  }
 ]
}