# A ClusterIP service for boss
apiVersion: v1
kind: Service
metadata:
  name: {{ include "diligent.boss.name" . }}
  labels:
    {{- include "diligent.commonLabels" . | nindent 4 }}
spec:
  ports:
    - port: 5710
      targetPort: 5710
  selector:
    {{- include "diligent.boss.selectorLabels" . | nindent 4 }}
