apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "diligent.grafana.name" . }}-prov-datasources
data:
  datasource.yml: |
    {{- tpl (.Files.Get "grafana-prov-datasource.yaml") . | nindent 4 }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "diligent.grafana.name" . }}-prov-dashboards
data:
  dashboards.yml: |
    {{- .Files.Get "grafana-prov-dashboards.yaml" | nindent 4 }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "diligent.grafana.name" . }}-dashboards
data:
  diligent.json: |
    {{- .Files.Get "grafana-dashboard.json" | nindent 4 }}
