# A ReplicaSet for grafana
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: {{ include "diligent.grafana.name" . }}
  labels:
    {{- include "diligent.commonLabels" . | nindent 4 }}
spec:
  replicas: 1

  selector:
    matchLabels:
      {{- include "diligent.grafana.selectorLabels" . | nindent 6 }}

  template:
    metadata:
      labels:
        {{- include "diligent.grafana.selectorLabels" . | nindent 8 }}
        {{- include "diligent.commonLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: diligent-grafana
          image: "{{ .Values.grafana.image.repo }}:{{ .Values.grafana.image.tag }}"
          imagePullPolicy: {{ .Values.boss.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/grafana
              name: grafana-storage
            - mountPath: /etc/grafana/provisioning/datasources
              name: grafana-prov-datasources
              readOnly: false
            - mountPath: /etc/grafana/provisioning/dashboards
              name: grafana-prov-dashboards
              readOnly: false
            - mountPath: /grafana/dashboards/diligent
              name: grafana-diligent-dashboards
              readOnly: false
      volumes:
        - name: grafana-storage
          emptyDir: {}
        - name: grafana-prov-datasources
          configMap:
            defaultMode: 420
            name: {{ include "diligent.grafana.name" . }}-prov-datasources
        - name: grafana-prov-dashboards
          configMap:
            defaultMode: 420
            name: {{ include "diligent.grafana.name" . }}-prov-dashboards
        - name: grafana-diligent-dashboards
          configMap:
            defaultMode: 420
            name: {{ include "diligent.grafana.name" . }}-dashboards
