# A Headless service for minions
apiVersion: v1
kind: Service
metadata:
  name: {{ include "diligent.minion.name" . }}
  labels:
    {{- include "diligent.commonLabels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - port: 5711
      targetPort: 5711
  selector:
    {{- include "diligent.minion.selectorLabels" . | nindent 4 }}

