{{- if .Values.prometheus.deployRbac -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "diligent.prometheus.name" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "diligent.prometheus.name" . }}
rules:
  - apiGroups: [""]
    resources:
      - services
      - endpoints
      - pods
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "diligent.prometheus.name" . }}
roleRef:
  kind: Role
  name: {{ include "diligent.prometheus.name" . }}
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: {{ include "diligent.prometheus.name" . }}
{{- end }}
