// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: diligent_boss.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BossPingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *BossPingRequest) Reset() {
	*x = BossPingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_diligent_boss_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BossPingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BossPingRequest) ProtoMessage() {}

func (x *BossPingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_diligent_boss_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BossPingRequest.ProtoReflect.Descriptor instead.
func (*BossPingRequest) Descriptor() ([]byte, []int) {
	return file_diligent_boss_proto_rawDescGZIP(), []int{0}
}

type BossPingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BuildInfo   *BuildInfo   `protobuf:"bytes,1,opt,name=build_info,json=buildInfo,proto3" json:"build_info,omitempty"`
	ProcessInfo *ProcessInfo `protobuf:"bytes,2,opt,name=process_info,json=processInfo,proto3" json:"process_info,omitempty"`
}

func (x *BossPingResponse) Reset() {
	*x = BossPingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_diligent_boss_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BossPingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BossPingResponse) ProtoMessage() {}

func (x *BossPingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_diligent_boss_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BossPingResponse.ProtoReflect.Descriptor instead.
func (*BossPingResponse) Descriptor() ([]byte, []int) {
	return file_diligent_boss_proto_rawDescGZIP(), []int{1}
}

func (x *BossPingResponse) GetBuildInfo() *BuildInfo {
	if x != nil {
		return x.BuildInfo
	}
	return nil
}

func (x *BossPingResponse) GetProcessInfo() *ProcessInfo {
	if x != nil {
		return x.ProcessInfo
	}
	return nil
}

type BossRegisterMinionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Addr string `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
}

func (x *BossRegisterMinionRequest) Reset() {
	*x = BossRegisterMinionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_diligent_boss_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BossRegisterMinionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BossRegisterMinionRequest) ProtoMessage() {}

func (x *BossRegisterMinionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_diligent_boss_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BossRegisterMinionRequest.ProtoReflect.Descriptor instead.
func (*BossRegisterMinionRequest) Descriptor() ([]byte, []int) {
	return file_diligent_boss_proto_rawDescGZIP(), []int{2}
}

func (x *BossRegisterMinionRequest) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

type BossRegisterMinionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status *GeneralStatus `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *BossRegisterMinionResponse) Reset() {
	*x = BossRegisterMinionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_diligent_boss_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BossRegisterMinionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BossRegisterMinionResponse) ProtoMessage() {}

func (x *BossRegisterMinionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_diligent_boss_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BossRegisterMinionResponse.ProtoReflect.Descriptor instead.
func (*BossRegisterMinionResponse) Descriptor() ([]byte, []int) {
	return file_diligent_boss_proto_rawDescGZIP(), []int{3}
}

func (x *BossRegisterMinionResponse) GetStatus() *GeneralStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

type BossUnregisterMinonRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Addr string `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
}

func (x *BossUnregisterMinonRequest) Reset() {
	*x = BossUnregisterMinonRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_diligent_boss_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BossUnregisterMinonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BossUnregisterMinonRequest) ProtoMessage() {}

func (x *BossUnregisterMinonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_diligent_boss_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BossUnregisterMinonRequest.ProtoReflect.Descriptor instead.
func (*BossUnregisterMinonRequest) Descriptor() ([]byte, []int) {
	return file_diligent_boss_proto_rawDescGZIP(), []int{4}
}

func (x *BossUnregisterMinonRequest) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

type BossUnregisterMinionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status *GeneralStatus `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *BossUnregisterMinionResponse) Reset() {
	*x = BossUnregisterMinionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_diligent_boss_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BossUnregisterMinionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BossUnregisterMinionResponse) ProtoMessage() {}

func (x *BossUnregisterMinionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_diligent_boss_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BossUnregisterMinionResponse.ProtoReflect.Descriptor instead.
func (*BossUnregisterMinionResponse) Descriptor() ([]byte, []int) {
	return file_diligent_boss_proto_rawDescGZIP(), []int{5}
}

func (x *BossUnregisterMinionResponse) GetStatus() *GeneralStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

type BossShowMinionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *BossShowMinionRequest) Reset() {
	*x = BossShowMinionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_diligent_boss_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BossShowMinionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BossShowMinionRequest) ProtoMessage() {}

func (x *BossShowMinionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_diligent_boss_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BossShowMinionRequest.ProtoReflect.Descriptor instead.
func (*BossShowMinionRequest) Descriptor() ([]byte, []int) {
	return file_diligent_boss_proto_rawDescGZIP(), []int{6}
}

type BossShowMinionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MinionInfos []*MinionInfo `protobuf:"bytes,1,rep,name=minion_infos,json=minionInfos,proto3" json:"minion_infos,omitempty"`
}

func (x *BossShowMinionResponse) Reset() {
	*x = BossShowMinionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_diligent_boss_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BossShowMinionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BossShowMinionResponse) ProtoMessage() {}

func (x *BossShowMinionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_diligent_boss_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BossShowMinionResponse.ProtoReflect.Descriptor instead.
func (*BossShowMinionResponse) Descriptor() ([]byte, []int) {
	return file_diligent_boss_proto_rawDescGZIP(), []int{7}
}

func (x *BossShowMinionResponse) GetMinionInfos() []*MinionInfo {
	if x != nil {
		return x.MinionInfos
	}
	return nil
}

type MinionInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Addr         string         `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	Reachability *GeneralStatus `protobuf:"bytes,2,opt,name=reachability,proto3" json:"reachability,omitempty"`
	BuildInfo    *BuildInfo     `protobuf:"bytes,3,opt,name=build_info,json=buildInfo,proto3" json:"build_info,omitempty"`
	ProcessInfo  *ProcessInfo   `protobuf:"bytes,4,opt,name=process_info,json=processInfo,proto3" json:"process_info,omitempty"`
}

func (x *MinionInfo) Reset() {
	*x = MinionInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_diligent_boss_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MinionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MinionInfo) ProtoMessage() {}

func (x *MinionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_diligent_boss_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MinionInfo.ProtoReflect.Descriptor instead.
func (*MinionInfo) Descriptor() ([]byte, []int) {
	return file_diligent_boss_proto_rawDescGZIP(), []int{8}
}

func (x *MinionInfo) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *MinionInfo) GetReachability() *GeneralStatus {
	if x != nil {
		return x.Reachability
	}
	return nil
}

func (x *MinionInfo) GetBuildInfo() *BuildInfo {
	if x != nil {
		return x.BuildInfo
	}
	return nil
}

func (x *MinionInfo) GetProcessInfo() *ProcessInfo {
	if x != nil {
		return x.ProcessInfo
	}
	return nil
}

type MinionStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Addr   string         `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	Status *GeneralStatus `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *MinionStatus) Reset() {
	*x = MinionStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_diligent_boss_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MinionStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MinionStatus) ProtoMessage() {}

func (x *MinionStatus) ProtoReflect() protoreflect.Message {
	mi := &file_diligent_boss_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MinionStatus.ProtoReflect.Descriptor instead.
func (*MinionStatus) Descriptor() ([]byte, []int) {
	return file_diligent_boss_proto_rawDescGZIP(), []int{9}
}

func (x *MinionStatus) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *MinionStatus) GetStatus() *GeneralStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

type BossPrepareJobRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JobSpec *JobSpec `protobuf:"bytes,1,opt,name=job_spec,json=jobSpec,proto3" json:"job_spec,omitempty"`
	JobDesc string   `protobuf:"bytes,2,opt,name=job_desc,json=jobDesc,proto3" json:"job_desc,omitempty"`
}

func (x *BossPrepareJobRequest) Reset() {
	*x = BossPrepareJobRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_diligent_boss_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BossPrepareJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BossPrepareJobRequest) ProtoMessage() {}

func (x *BossPrepareJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_diligent_boss_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BossPrepareJobRequest.ProtoReflect.Descriptor instead.
func (*BossPrepareJobRequest) Descriptor() ([]byte, []int) {
	return file_diligent_boss_proto_rawDescGZIP(), []int{10}
}

func (x *BossPrepareJobRequest) GetJobSpec() *JobSpec {
	if x != nil {
		return x.JobSpec
	}
	return nil
}

func (x *BossPrepareJobRequest) GetJobDesc() string {
	if x != nil {
		return x.JobDesc
	}
	return ""
}

type BossPrepareJobResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JobId          string          `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	OverallStatus  *GeneralStatus  `protobuf:"bytes,2,opt,name=overall_status,json=overallStatus,proto3" json:"overall_status,omitempty"`
	MinionStatuses []*MinionStatus `protobuf:"bytes,3,rep,name=minion_statuses,json=minionStatuses,proto3" json:"minion_statuses,omitempty"`
}

func (x *BossPrepareJobResponse) Reset() {
	*x = BossPrepareJobResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_diligent_boss_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BossPrepareJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BossPrepareJobResponse) ProtoMessage() {}

func (x *BossPrepareJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_diligent_boss_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BossPrepareJobResponse.ProtoReflect.Descriptor instead.
func (*BossPrepareJobResponse) Descriptor() ([]byte, []int) {
	return file_diligent_boss_proto_rawDescGZIP(), []int{11}
}

func (x *BossPrepareJobResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *BossPrepareJobResponse) GetOverallStatus() *GeneralStatus {
	if x != nil {
		return x.OverallStatus
	}
	return nil
}

func (x *BossPrepareJobResponse) GetMinionStatuses() []*MinionStatus {
	if x != nil {
		return x.MinionStatuses
	}
	return nil
}

type BossRunJobRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *BossRunJobRequest) Reset() {
	*x = BossRunJobRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_diligent_boss_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BossRunJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BossRunJobRequest) ProtoMessage() {}

func (x *BossRunJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_diligent_boss_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BossRunJobRequest.ProtoReflect.Descriptor instead.
func (*BossRunJobRequest) Descriptor() ([]byte, []int) {
	return file_diligent_boss_proto_rawDescGZIP(), []int{12}
}

type BossRunJobResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OverallStatus  *GeneralStatus  `protobuf:"bytes,1,opt,name=overall_status,json=overallStatus,proto3" json:"overall_status,omitempty"`
	MinionStatuses []*MinionStatus `protobuf:"bytes,2,rep,name=minion_statuses,json=minionStatuses,proto3" json:"minion_statuses,omitempty"`
}

func (x *BossRunJobResponse) Reset() {
	*x = BossRunJobResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_diligent_boss_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BossRunJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BossRunJobResponse) ProtoMessage() {}

func (x *BossRunJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_diligent_boss_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BossRunJobResponse.ProtoReflect.Descriptor instead.
func (*BossRunJobResponse) Descriptor() ([]byte, []int) {
	return file_diligent_boss_proto_rawDescGZIP(), []int{13}
}

func (x *BossRunJobResponse) GetOverallStatus() *GeneralStatus {
	if x != nil {
		return x.OverallStatus
	}
	return nil
}

func (x *BossRunJobResponse) GetMinionStatuses() []*MinionStatus {
	if x != nil {
		return x.MinionStatuses
	}
	return nil
}

type BossStopJobRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *BossStopJobRequest) Reset() {
	*x = BossStopJobRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_diligent_boss_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BossStopJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BossStopJobRequest) ProtoMessage() {}

func (x *BossStopJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_diligent_boss_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BossStopJobRequest.ProtoReflect.Descriptor instead.
func (*BossStopJobRequest) Descriptor() ([]byte, []int) {
	return file_diligent_boss_proto_rawDescGZIP(), []int{14}
}

type BossStopJobResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OverallStatus  *GeneralStatus  `protobuf:"bytes,1,opt,name=overall_status,json=overallStatus,proto3" json:"overall_status,omitempty"`
	MinionStatuses []*MinionStatus `protobuf:"bytes,2,rep,name=minion_statuses,json=minionStatuses,proto3" json:"minion_statuses,omitempty"`
}

func (x *BossStopJobResponse) Reset() {
	*x = BossStopJobResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_diligent_boss_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BossStopJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BossStopJobResponse) ProtoMessage() {}

func (x *BossStopJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_diligent_boss_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BossStopJobResponse.ProtoReflect.Descriptor instead.
func (*BossStopJobResponse) Descriptor() ([]byte, []int) {
	return file_diligent_boss_proto_rawDescGZIP(), []int{15}
}

func (x *BossStopJobResponse) GetOverallStatus() *GeneralStatus {
	if x != nil {
		return x.OverallStatus
	}
	return nil
}

func (x *BossStopJobResponse) GetMinionStatuses() []*MinionStatus {
	if x != nil {
		return x.MinionStatuses
	}
	return nil
}

var File_diligent_boss_proto protoreflect.FileDescriptor

var file_diligent_boss_proto_rawDesc = []byte{
	0x0a, 0x13, 0x64, 0x69, 0x6c, 0x69, 0x67, 0x65, 0x6e, 0x74, 0x5f, 0x62, 0x6f, 0x73, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x15, 0x64, 0x69,
	0x6c, 0x69, 0x67, 0x65, 0x6e, 0x74, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x11, 0x0a, 0x0f, 0x42, 0x6f, 0x73, 0x73, 0x50, 0x69, 0x6e, 0x67, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x7a, 0x0a, 0x10, 0x42, 0x6f, 0x73, 0x73, 0x50, 0x69,
	0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2f, 0x0a, 0x0a, 0x62, 0x75,
	0x69, 0x6c, 0x64, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x09, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x35, 0x0a, 0x0c, 0x70,
	0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73,
	0x73, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0b, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x49, 0x6e,
	0x66, 0x6f, 0x22, 0x2f, 0x0a, 0x19, 0x42, 0x6f, 0x73, 0x73, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74,
	0x65, 0x72, 0x4d, 0x69, 0x6e, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x61, 0x64, 0x64, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x61,
	0x64, 0x64, 0x72, 0x22, 0x4a, 0x0a, 0x1a, 0x42, 0x6f, 0x73, 0x73, 0x52, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x65, 0x72, 0x4d, 0x69, 0x6e, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x2c, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61,
	0x6c, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22,
	0x30, 0x0a, 0x1a, 0x42, 0x6f, 0x73, 0x73, 0x55, 0x6e, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65,
	0x72, 0x4d, 0x69, 0x6e, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x61, 0x64, 0x64, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x61, 0x64, 0x64,
	0x72, 0x22, 0x4c, 0x0a, 0x1c, 0x42, 0x6f, 0x73, 0x73, 0x55, 0x6e, 0x72, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x65, 0x72, 0x4d, 0x69, 0x6e, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x2c, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61,
	0x6c, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22,
	0x17, 0x0a, 0x15, 0x42, 0x6f, 0x73, 0x73, 0x53, 0x68, 0x6f, 0x77, 0x4d, 0x69, 0x6e, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x4e, 0x0a, 0x16, 0x42, 0x6f, 0x73, 0x73,
	0x53, 0x68, 0x6f, 0x77, 0x4d, 0x69, 0x6e, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x34, 0x0a, 0x0c, 0x6d, 0x69, 0x6e, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x6e, 0x66,
	0x6f, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x4d, 0x69, 0x6e, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0b, 0x6d, 0x69, 0x6e,
	0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x73, 0x22, 0xc2, 0x01, 0x0a, 0x0a, 0x4d, 0x69, 0x6e,
	0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x64, 0x64, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x61, 0x64, 0x64, 0x72, 0x12, 0x38, 0x0a, 0x0c, 0x72,
	0x65, 0x61, 0x63, 0x68, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61,
	0x6c, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x0c, 0x72, 0x65, 0x61, 0x63, 0x68, 0x61, 0x62,
	0x69, 0x6c, 0x69, 0x74, 0x79, 0x12, 0x2f, 0x0a, 0x0a, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x5f, 0x69,
	0x6e, 0x66, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x09, 0x62, 0x75, 0x69,
	0x6c, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x35, 0x0a, 0x0c, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73,
	0x73, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x0b, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x50, 0x0a,
	0x0c, 0x4d, 0x69, 0x6e, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x12, 0x0a,
	0x04, 0x61, 0x64, 0x64, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x61, 0x64, 0x64,
	0x72, 0x12, 0x2c, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61,
	0x6c, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22,
	0x5d, 0x0a, 0x15, 0x42, 0x6f, 0x73, 0x73, 0x50, 0x72, 0x65, 0x70, 0x61, 0x72, 0x65, 0x4a, 0x6f,
	0x62, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x29, 0x0a, 0x08, 0x6a, 0x6f, 0x62, 0x5f,
	0x73, 0x70, 0x65, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x4a, 0x6f, 0x62, 0x53, 0x70, 0x65, 0x63, 0x52, 0x07, 0x6a, 0x6f, 0x62, 0x53,
	0x70, 0x65, 0x63, 0x12, 0x19, 0x0a, 0x08, 0x6a, 0x6f, 0x62, 0x5f, 0x64, 0x65, 0x73, 0x63, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6a, 0x6f, 0x62, 0x44, 0x65, 0x73, 0x63, 0x22, 0xaa,
	0x01, 0x0a, 0x16, 0x42, 0x6f, 0x73, 0x73, 0x50, 0x72, 0x65, 0x70, 0x61, 0x72, 0x65, 0x4a, 0x6f,
	0x62, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x15, 0x0a, 0x06, 0x6a, 0x6f, 0x62,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6a, 0x6f, 0x62, 0x49, 0x64,
	0x12, 0x3b, 0x0a, 0x0e, 0x6f, 0x76, 0x65, 0x72, 0x61, 0x6c, 0x6c, 0x5f, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x0d,
	0x6f, 0x76, 0x65, 0x72, 0x61, 0x6c, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x3c, 0x0a,
	0x0f, 0x6d, 0x69, 0x6e, 0x69, 0x6f, 0x6e, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x65, 0x73,
	0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4d,
	0x69, 0x6e, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x0e, 0x6d, 0x69, 0x6e,
	0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x65, 0x73, 0x22, 0x13, 0x0a, 0x11, 0x42,
	0x6f, 0x73, 0x73, 0x52, 0x75, 0x6e, 0x4a, 0x6f, 0x62, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x22, 0x8f, 0x01, 0x0a, 0x12, 0x42, 0x6f, 0x73, 0x73, 0x52, 0x75, 0x6e, 0x4a, 0x6f, 0x62, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3b, 0x0a, 0x0e, 0x6f, 0x76, 0x65, 0x72, 0x61,
	0x6c, 0x6c, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x6c, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x0d, 0x6f, 0x76, 0x65, 0x72, 0x61, 0x6c, 0x6c, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x3c, 0x0a, 0x0f, 0x6d, 0x69, 0x6e, 0x69, 0x6f, 0x6e, 0x5f, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4d, 0x69, 0x6e, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x52, 0x0e, 0x6d, 0x69, 0x6e, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x65, 0x73, 0x22, 0x14, 0x0a, 0x12, 0x42, 0x6f, 0x73, 0x73, 0x53, 0x74, 0x6f, 0x70, 0x4a, 0x6f,
	0x62, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x90, 0x01, 0x0a, 0x13, 0x42, 0x6f, 0x73,
	0x73, 0x53, 0x74, 0x6f, 0x70, 0x4a, 0x6f, 0x62, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x3b, 0x0a, 0x0e, 0x6f, 0x76, 0x65, 0x72, 0x61, 0x6c, 0x6c, 0x5f, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x0d,
	0x6f, 0x76, 0x65, 0x72, 0x61, 0x6c, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x3c, 0x0a,
	0x0f, 0x6d, 0x69, 0x6e, 0x69, 0x6f, 0x6e, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x65, 0x73,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4d,
	0x69, 0x6e, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x0e, 0x6d, 0x69, 0x6e,
	0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x65, 0x73, 0x32, 0x8a, 0x04, 0x0a, 0x04,
	0x42, 0x6f, 0x73, 0x73, 0x12, 0x37, 0x0a, 0x04, 0x50, 0x69, 0x6e, 0x67, 0x12, 0x16, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x6f, 0x73, 0x73, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x6f, 0x73,
	0x73, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x55, 0x0a,
	0x0e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x4d, 0x69, 0x6e, 0x69, 0x6f, 0x6e, 0x12,
	0x20, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x6f, 0x73, 0x73, 0x52, 0x65, 0x67, 0x69,
	0x73, 0x74, 0x65, 0x72, 0x4d, 0x69, 0x6e, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x21, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x6f, 0x73, 0x73, 0x52, 0x65,
	0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x4d, 0x69, 0x6e, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5a, 0x0a, 0x10, 0x55, 0x6e, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74,
	0x65, 0x72, 0x4d, 0x69, 0x6e, 0x69, 0x6f, 0x6e, 0x12, 0x21, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x42, 0x6f, 0x73, 0x73, 0x55, 0x6e, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x4d,
	0x69, 0x6e, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x6f, 0x73, 0x73, 0x55, 0x6e, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74,
	0x65, 0x72, 0x4d, 0x69, 0x6e, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x4a, 0x0a, 0x0b, 0x53, 0x68, 0x6f, 0x77, 0x4d, 0x69, 0x6e, 0x69, 0x6f, 0x6e, 0x73, 0x12,
	0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x6f, 0x73, 0x73, 0x53, 0x68, 0x6f, 0x77,
	0x4d, 0x69, 0x6e, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x6f, 0x73, 0x73, 0x53, 0x68, 0x6f, 0x77, 0x4d, 0x69,
	0x6e, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x49, 0x0a, 0x0a,
	0x50, 0x72, 0x65, 0x70, 0x61, 0x72, 0x65, 0x4a, 0x6f, 0x62, 0x12, 0x1c, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x42, 0x6f, 0x73, 0x73, 0x50, 0x72, 0x65, 0x70, 0x61, 0x72, 0x65, 0x4a, 0x6f,
	0x62, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x42, 0x6f, 0x73, 0x73, 0x50, 0x72, 0x65, 0x70, 0x61, 0x72, 0x65, 0x4a, 0x6f, 0x62, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3d, 0x0a, 0x06, 0x52, 0x75, 0x6e, 0x4a, 0x6f,
	0x62, 0x12, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x6f, 0x73, 0x73, 0x52, 0x75,
	0x6e, 0x4a, 0x6f, 0x62, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x6f, 0x73, 0x73, 0x52, 0x75, 0x6e, 0x4a, 0x6f, 0x62, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x40, 0x0a, 0x07, 0x53, 0x74, 0x6f, 0x70, 0x4a, 0x6f,
	0x62, 0x12, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x6f, 0x73, 0x73, 0x53, 0x74,
	0x6f, 0x70, 0x4a, 0x6f, 0x62, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x6f, 0x73, 0x73, 0x53, 0x74, 0x6f, 0x70, 0x4a, 0x6f, 0x62,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_diligent_boss_proto_rawDescOnce sync.Once
	file_diligent_boss_proto_rawDescData = file_diligent_boss_proto_rawDesc
)

func file_diligent_boss_proto_rawDescGZIP() []byte {
	file_diligent_boss_proto_rawDescOnce.Do(func() {
		file_diligent_boss_proto_rawDescData = protoimpl.X.CompressGZIP(file_diligent_boss_proto_rawDescData)
	})
	return file_diligent_boss_proto_rawDescData
}

var file_diligent_boss_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_diligent_boss_proto_goTypes = []interface{}{
	(*BossPingRequest)(nil),              // 0: proto.BossPingRequest
	(*BossPingResponse)(nil),             // 1: proto.BossPingResponse
	(*BossRegisterMinionRequest)(nil),    // 2: proto.BossRegisterMinionRequest
	(*BossRegisterMinionResponse)(nil),   // 3: proto.BossRegisterMinionResponse
	(*BossUnregisterMinonRequest)(nil),   // 4: proto.BossUnregisterMinonRequest
	(*BossUnregisterMinionResponse)(nil), // 5: proto.BossUnregisterMinionResponse
	(*BossShowMinionRequest)(nil),        // 6: proto.BossShowMinionRequest
	(*BossShowMinionResponse)(nil),       // 7: proto.BossShowMinionResponse
	(*MinionInfo)(nil),                   // 8: proto.MinionInfo
	(*MinionStatus)(nil),                 // 9: proto.MinionStatus
	(*BossPrepareJobRequest)(nil),        // 10: proto.BossPrepareJobRequest
	(*BossPrepareJobResponse)(nil),       // 11: proto.BossPrepareJobResponse
	(*BossRunJobRequest)(nil),            // 12: proto.BossRunJobRequest
	(*BossRunJobResponse)(nil),           // 13: proto.BossRunJobResponse
	(*BossStopJobRequest)(nil),           // 14: proto.BossStopJobRequest
	(*BossStopJobResponse)(nil),          // 15: proto.BossStopJobResponse
	(*BuildInfo)(nil),                    // 16: proto.BuildInfo
	(*ProcessInfo)(nil),                  // 17: proto.ProcessInfo
	(*GeneralStatus)(nil),                // 18: proto.GeneralStatus
	(*JobSpec)(nil),                      // 19: proto.JobSpec
}
var file_diligent_boss_proto_depIdxs = []int32{
	16, // 0: proto.BossPingResponse.build_info:type_name -> proto.BuildInfo
	17, // 1: proto.BossPingResponse.process_info:type_name -> proto.ProcessInfo
	18, // 2: proto.BossRegisterMinionResponse.status:type_name -> proto.GeneralStatus
	18, // 3: proto.BossUnregisterMinionResponse.status:type_name -> proto.GeneralStatus
	8,  // 4: proto.BossShowMinionResponse.minion_infos:type_name -> proto.MinionInfo
	18, // 5: proto.MinionInfo.reachability:type_name -> proto.GeneralStatus
	16, // 6: proto.MinionInfo.build_info:type_name -> proto.BuildInfo
	17, // 7: proto.MinionInfo.process_info:type_name -> proto.ProcessInfo
	18, // 8: proto.MinionStatus.status:type_name -> proto.GeneralStatus
	19, // 9: proto.BossPrepareJobRequest.job_spec:type_name -> proto.JobSpec
	18, // 10: proto.BossPrepareJobResponse.overall_status:type_name -> proto.GeneralStatus
	9,  // 11: proto.BossPrepareJobResponse.minion_statuses:type_name -> proto.MinionStatus
	18, // 12: proto.BossRunJobResponse.overall_status:type_name -> proto.GeneralStatus
	9,  // 13: proto.BossRunJobResponse.minion_statuses:type_name -> proto.MinionStatus
	18, // 14: proto.BossStopJobResponse.overall_status:type_name -> proto.GeneralStatus
	9,  // 15: proto.BossStopJobResponse.minion_statuses:type_name -> proto.MinionStatus
	0,  // 16: proto.Boss.Ping:input_type -> proto.BossPingRequest
	2,  // 17: proto.Boss.RegisterMinion:input_type -> proto.BossRegisterMinionRequest
	4,  // 18: proto.Boss.UnregisterMinion:input_type -> proto.BossUnregisterMinonRequest
	6,  // 19: proto.Boss.ShowMinions:input_type -> proto.BossShowMinionRequest
	10, // 20: proto.Boss.PrepareJob:input_type -> proto.BossPrepareJobRequest
	12, // 21: proto.Boss.RunJob:input_type -> proto.BossRunJobRequest
	14, // 22: proto.Boss.StopJob:input_type -> proto.BossStopJobRequest
	1,  // 23: proto.Boss.Ping:output_type -> proto.BossPingResponse
	3,  // 24: proto.Boss.RegisterMinion:output_type -> proto.BossRegisterMinionResponse
	5,  // 25: proto.Boss.UnregisterMinion:output_type -> proto.BossUnregisterMinionResponse
	7,  // 26: proto.Boss.ShowMinions:output_type -> proto.BossShowMinionResponse
	11, // 27: proto.Boss.PrepareJob:output_type -> proto.BossPrepareJobResponse
	13, // 28: proto.Boss.RunJob:output_type -> proto.BossRunJobResponse
	15, // 29: proto.Boss.StopJob:output_type -> proto.BossStopJobResponse
	23, // [23:30] is the sub-list for method output_type
	16, // [16:23] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_diligent_boss_proto_init() }
func file_diligent_boss_proto_init() {
	if File_diligent_boss_proto != nil {
		return
	}
	file_diligent_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_diligent_boss_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BossPingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_diligent_boss_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BossPingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_diligent_boss_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BossRegisterMinionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_diligent_boss_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BossRegisterMinionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_diligent_boss_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BossUnregisterMinonRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_diligent_boss_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BossUnregisterMinionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_diligent_boss_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BossShowMinionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_diligent_boss_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BossShowMinionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_diligent_boss_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MinionInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_diligent_boss_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MinionStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_diligent_boss_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BossPrepareJobRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_diligent_boss_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BossPrepareJobResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_diligent_boss_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BossRunJobRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_diligent_boss_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BossRunJobResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_diligent_boss_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BossStopJobRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_diligent_boss_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BossStopJobResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_diligent_boss_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_diligent_boss_proto_goTypes,
		DependencyIndexes: file_diligent_boss_proto_depIdxs,
		MessageInfos:      file_diligent_boss_proto_msgTypes,
	}.Build()
	File_diligent_boss_proto = out.File
	file_diligent_boss_proto_rawDesc = nil
	file_diligent_boss_proto_goTypes = nil
	file_diligent_boss_proto_depIdxs = nil
}
