// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: diligent_minion.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MinionPingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MinionPingRequest) Reset() {
	*x = MinionPingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_diligent_minion_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MinionPingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MinionPingRequest) ProtoMessage() {}

func (x *MinionPingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_diligent_minion_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MinionPingRequest.ProtoReflect.Descriptor instead.
func (*MinionPingRequest) Descriptor() ([]byte, []int) {
	return file_diligent_minion_proto_rawDescGZIP(), []int{0}
}

type MinionPingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BuildInfo   *BuildInfo   `protobuf:"bytes,1,opt,name=build_info,json=buildInfo,proto3" json:"build_info,omitempty"`
	ProcessInfo *ProcessInfo `protobuf:"bytes,2,opt,name=process_info,json=processInfo,proto3" json:"process_info,omitempty"`
}

func (x *MinionPingResponse) Reset() {
	*x = MinionPingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_diligent_minion_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MinionPingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MinionPingResponse) ProtoMessage() {}

func (x *MinionPingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_diligent_minion_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MinionPingResponse.ProtoReflect.Descriptor instead.
func (*MinionPingResponse) Descriptor() ([]byte, []int) {
	return file_diligent_minion_proto_rawDescGZIP(), []int{1}
}

func (x *MinionPingResponse) GetBuildInfo() *BuildInfo {
	if x != nil {
		return x.BuildInfo
	}
	return nil
}

func (x *MinionPingResponse) GetProcessInfo() *ProcessInfo {
	if x != nil {
		return x.ProcessInfo
	}
	return nil
}

type MinionPrepareJobRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JobId   string   `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	JobDesc string   `protobuf:"bytes,2,opt,name=job_desc,json=jobDesc,proto3" json:"job_desc,omitempty"`
	JobSpec *JobSpec `protobuf:"bytes,3,opt,name=job_spec,json=jobSpec,proto3" json:"job_spec,omitempty"`
}

func (x *MinionPrepareJobRequest) Reset() {
	*x = MinionPrepareJobRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_diligent_minion_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MinionPrepareJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MinionPrepareJobRequest) ProtoMessage() {}

func (x *MinionPrepareJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_diligent_minion_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MinionPrepareJobRequest.ProtoReflect.Descriptor instead.
func (*MinionPrepareJobRequest) Descriptor() ([]byte, []int) {
	return file_diligent_minion_proto_rawDescGZIP(), []int{2}
}

func (x *MinionPrepareJobRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *MinionPrepareJobRequest) GetJobDesc() string {
	if x != nil {
		return x.JobDesc
	}
	return ""
}

func (x *MinionPrepareJobRequest) GetJobSpec() *JobSpec {
	if x != nil {
		return x.JobSpec
	}
	return nil
}

type MinionPrepareJobResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status *GeneralStatus `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *MinionPrepareJobResponse) Reset() {
	*x = MinionPrepareJobResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_diligent_minion_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MinionPrepareJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MinionPrepareJobResponse) ProtoMessage() {}

func (x *MinionPrepareJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_diligent_minion_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MinionPrepareJobResponse.ProtoReflect.Descriptor instead.
func (*MinionPrepareJobResponse) Descriptor() ([]byte, []int) {
	return file_diligent_minion_proto_rawDescGZIP(), []int{3}
}

func (x *MinionPrepareJobResponse) GetStatus() *GeneralStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

type MinionRunJobRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MinionRunJobRequest) Reset() {
	*x = MinionRunJobRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_diligent_minion_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MinionRunJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MinionRunJobRequest) ProtoMessage() {}

func (x *MinionRunJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_diligent_minion_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MinionRunJobRequest.ProtoReflect.Descriptor instead.
func (*MinionRunJobRequest) Descriptor() ([]byte, []int) {
	return file_diligent_minion_proto_rawDescGZIP(), []int{4}
}

type MinionRunJobResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status *GeneralStatus `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *MinionRunJobResponse) Reset() {
	*x = MinionRunJobResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_diligent_minion_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MinionRunJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MinionRunJobResponse) ProtoMessage() {}

func (x *MinionRunJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_diligent_minion_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MinionRunJobResponse.ProtoReflect.Descriptor instead.
func (*MinionRunJobResponse) Descriptor() ([]byte, []int) {
	return file_diligent_minion_proto_rawDescGZIP(), []int{5}
}

func (x *MinionRunJobResponse) GetStatus() *GeneralStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

type MinionStopJobRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MinionStopJobRequest) Reset() {
	*x = MinionStopJobRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_diligent_minion_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MinionStopJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MinionStopJobRequest) ProtoMessage() {}

func (x *MinionStopJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_diligent_minion_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MinionStopJobRequest.ProtoReflect.Descriptor instead.
func (*MinionStopJobRequest) Descriptor() ([]byte, []int) {
	return file_diligent_minion_proto_rawDescGZIP(), []int{6}
}

type MinionStopJobResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status *GeneralStatus `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *MinionStopJobResponse) Reset() {
	*x = MinionStopJobResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_diligent_minion_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MinionStopJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MinionStopJobResponse) ProtoMessage() {}

func (x *MinionStopJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_diligent_minion_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MinionStopJobResponse.ProtoReflect.Descriptor instead.
func (*MinionStopJobResponse) Descriptor() ([]byte, []int) {
	return file_diligent_minion_proto_rawDescGZIP(), []int{7}
}

func (x *MinionStopJobResponse) GetStatus() *GeneralStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

type MinionGetDataSpecInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MinionGetDataSpecInfoRequest) Reset() {
	*x = MinionGetDataSpecInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_diligent_minion_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MinionGetDataSpecInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MinionGetDataSpecInfoRequest) ProtoMessage() {}

func (x *MinionGetDataSpecInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_diligent_minion_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MinionGetDataSpecInfoRequest.ProtoReflect.Descriptor instead.
func (*MinionGetDataSpecInfoRequest) Descriptor() ([]byte, []int) {
	return file_diligent_minion_proto_rawDescGZIP(), []int{8}
}

type MinionGetDataSpecInfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status       *GeneralStatus `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	DataSpecInfo *DataSpecInfo  `protobuf:"bytes,2,opt,name=data_spec_info,json=dataSpecInfo,proto3" json:"data_spec_info,omitempty"`
}

func (x *MinionGetDataSpecInfoResponse) Reset() {
	*x = MinionGetDataSpecInfoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_diligent_minion_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MinionGetDataSpecInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MinionGetDataSpecInfoResponse) ProtoMessage() {}

func (x *MinionGetDataSpecInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_diligent_minion_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MinionGetDataSpecInfoResponse.ProtoReflect.Descriptor instead.
func (*MinionGetDataSpecInfoResponse) Descriptor() ([]byte, []int) {
	return file_diligent_minion_proto_rawDescGZIP(), []int{9}
}

func (x *MinionGetDataSpecInfoResponse) GetStatus() *GeneralStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *MinionGetDataSpecInfoResponse) GetDataSpecInfo() *DataSpecInfo {
	if x != nil {
		return x.DataSpecInfo
	}
	return nil
}

type MinionGetDBConnectionInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MinionGetDBConnectionInfoRequest) Reset() {
	*x = MinionGetDBConnectionInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_diligent_minion_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MinionGetDBConnectionInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MinionGetDBConnectionInfoRequest) ProtoMessage() {}

func (x *MinionGetDBConnectionInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_diligent_minion_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MinionGetDBConnectionInfoRequest.ProtoReflect.Descriptor instead.
func (*MinionGetDBConnectionInfoRequest) Descriptor() ([]byte, []int) {
	return file_diligent_minion_proto_rawDescGZIP(), []int{10}
}

type MinionGetDBConnectionInfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status *GeneralStatus `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	DbSpec *DBSpec        `protobuf:"bytes,2,opt,name=db_spec,json=dbSpec,proto3" json:"db_spec,omitempty"`
}

func (x *MinionGetDBConnectionInfoResponse) Reset() {
	*x = MinionGetDBConnectionInfoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_diligent_minion_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MinionGetDBConnectionInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MinionGetDBConnectionInfoResponse) ProtoMessage() {}

func (x *MinionGetDBConnectionInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_diligent_minion_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MinionGetDBConnectionInfoResponse.ProtoReflect.Descriptor instead.
func (*MinionGetDBConnectionInfoResponse) Descriptor() ([]byte, []int) {
	return file_diligent_minion_proto_rawDescGZIP(), []int{11}
}

func (x *MinionGetDBConnectionInfoResponse) GetStatus() *GeneralStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *MinionGetDBConnectionInfoResponse) GetDbSpec() *DBSpec {
	if x != nil {
		return x.DbSpec
	}
	return nil
}

type MinionGetWorkloadInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MinionGetWorkloadInfoRequest) Reset() {
	*x = MinionGetWorkloadInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_diligent_minion_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MinionGetWorkloadInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MinionGetWorkloadInfoRequest) ProtoMessage() {}

func (x *MinionGetWorkloadInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_diligent_minion_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MinionGetWorkloadInfoRequest.ProtoReflect.Descriptor instead.
func (*MinionGetWorkloadInfoRequest) Descriptor() ([]byte, []int) {
	return file_diligent_minion_proto_rawDescGZIP(), []int{12}
}

type MinionGetWorkloadInfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status       *GeneralStatus `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	WorkloadSpec *WorkloadSpec  `protobuf:"bytes,2,opt,name=workload_spec,json=workloadSpec,proto3" json:"workload_spec,omitempty"`
	IsRunning    bool           `protobuf:"varint,3,opt,name=is_running,json=isRunning,proto3" json:"is_running,omitempty"`
}

func (x *MinionGetWorkloadInfoResponse) Reset() {
	*x = MinionGetWorkloadInfoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_diligent_minion_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MinionGetWorkloadInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MinionGetWorkloadInfoResponse) ProtoMessage() {}

func (x *MinionGetWorkloadInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_diligent_minion_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MinionGetWorkloadInfoResponse.ProtoReflect.Descriptor instead.
func (*MinionGetWorkloadInfoResponse) Descriptor() ([]byte, []int) {
	return file_diligent_minion_proto_rawDescGZIP(), []int{13}
}

func (x *MinionGetWorkloadInfoResponse) GetStatus() *GeneralStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *MinionGetWorkloadInfoResponse) GetWorkloadSpec() *WorkloadSpec {
	if x != nil {
		return x.WorkloadSpec
	}
	return nil
}

func (x *MinionGetWorkloadInfoResponse) GetIsRunning() bool {
	if x != nil {
		return x.IsRunning
	}
	return false
}

var File_diligent_minion_proto protoreflect.FileDescriptor

var file_diligent_minion_proto_rawDesc = []byte{
	0x0a, 0x15, 0x64, 0x69, 0x6c, 0x69, 0x67, 0x65, 0x6e, 0x74, 0x5f, 0x6d, 0x69, 0x6e, 0x69, 0x6f,
	0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x15,
	0x64, 0x69, 0x6c, 0x69, 0x67, 0x65, 0x6e, 0x74, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x13, 0x0a, 0x11, 0x4d, 0x69, 0x6e, 0x69, 0x6f, 0x6e, 0x50,
	0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x7c, 0x0a, 0x12, 0x4d, 0x69,
	0x6e, 0x69, 0x6f, 0x6e, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x2f, 0x0a, 0x0a, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x75, 0x69,
	0x6c, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x09, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x49, 0x6e, 0x66,
	0x6f, 0x12, 0x35, 0x0a, 0x0c, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x69, 0x6e, 0x66,
	0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0b, 0x70, 0x72, 0x6f,
	0x63, 0x65, 0x73, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x76, 0x0a, 0x17, 0x4d, 0x69, 0x6e, 0x69,
	0x6f, 0x6e, 0x50, 0x72, 0x65, 0x70, 0x61, 0x72, 0x65, 0x4a, 0x6f, 0x62, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x6a, 0x6f, 0x62, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x6a, 0x6f, 0x62, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x6a, 0x6f,
	0x62, 0x5f, 0x64, 0x65, 0x73, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6a, 0x6f,
	0x62, 0x44, 0x65, 0x73, 0x63, 0x12, 0x29, 0x0a, 0x08, 0x6a, 0x6f, 0x62, 0x5f, 0x73, 0x70, 0x65,
	0x63, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x4a, 0x6f, 0x62, 0x53, 0x70, 0x65, 0x63, 0x52, 0x07, 0x6a, 0x6f, 0x62, 0x53, 0x70, 0x65, 0x63,
	0x22, 0x48, 0x0a, 0x18, 0x4d, 0x69, 0x6e, 0x69, 0x6f, 0x6e, 0x50, 0x72, 0x65, 0x70, 0x61, 0x72,
	0x65, 0x4a, 0x6f, 0x62, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2c, 0x0a, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x6c, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x15, 0x0a, 0x13, 0x4d, 0x69,
	0x6e, 0x69, 0x6f, 0x6e, 0x52, 0x75, 0x6e, 0x4a, 0x6f, 0x62, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x22, 0x44, 0x0a, 0x14, 0x4d, 0x69, 0x6e, 0x69, 0x6f, 0x6e, 0x52, 0x75, 0x6e, 0x4a, 0x6f,
	0x62, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2c, 0x0a, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x16, 0x0a, 0x14, 0x4d, 0x69, 0x6e, 0x69, 0x6f,
	0x6e, 0x53, 0x74, 0x6f, 0x70, 0x4a, 0x6f, 0x62, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22,
	0x45, 0x0a, 0x15, 0x4d, 0x69, 0x6e, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x6f, 0x70, 0x4a, 0x6f, 0x62,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2c, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x1e, 0x0a, 0x1c, 0x4d, 0x69, 0x6e, 0x69, 0x6f, 0x6e,
	0x47, 0x65, 0x74, 0x44, 0x61, 0x74, 0x61, 0x53, 0x70, 0x65, 0x63, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x88, 0x01, 0x0a, 0x1d, 0x4d, 0x69, 0x6e, 0x69, 0x6f,
	0x6e, 0x47, 0x65, 0x74, 0x44, 0x61, 0x74, 0x61, 0x53, 0x70, 0x65, 0x63, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2c, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x39, 0x0a, 0x0e, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x73,
	0x70, 0x65, 0x63, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x53, 0x70, 0x65, 0x63, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x0c, 0x64, 0x61, 0x74, 0x61, 0x53, 0x70, 0x65, 0x63, 0x49, 0x6e, 0x66,
	0x6f, 0x22, 0x22, 0x0a, 0x20, 0x4d, 0x69, 0x6e, 0x69, 0x6f, 0x6e, 0x47, 0x65, 0x74, 0x44, 0x42,
	0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x79, 0x0a, 0x21, 0x4d, 0x69, 0x6e, 0x69, 0x6f, 0x6e, 0x47,
	0x65, 0x74, 0x44, 0x42, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2c, 0x0a, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x26, 0x0a, 0x07, 0x64, 0x62, 0x5f, 0x73,
	0x70, 0x65, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x44, 0x42, 0x53, 0x70, 0x65, 0x63, 0x52, 0x06, 0x64, 0x62, 0x53, 0x70, 0x65, 0x63,
	0x22, 0x1e, 0x0a, 0x1c, 0x4d, 0x69, 0x6e, 0x69, 0x6f, 0x6e, 0x47, 0x65, 0x74, 0x57, 0x6f, 0x72,
	0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x22, 0xa6, 0x01, 0x0a, 0x1d, 0x4d, 0x69, 0x6e, 0x69, 0x6f, 0x6e, 0x47, 0x65, 0x74, 0x57, 0x6f,
	0x72, 0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x2c, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72,
	0x61, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x38, 0x0a, 0x0d, 0x77, 0x6f, 0x72, 0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x73, 0x70, 0x65,
	0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x57, 0x6f, 0x72, 0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x53, 0x70, 0x65, 0x63, 0x52, 0x0c, 0x77, 0x6f,
	0x72, 0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x53, 0x70, 0x65, 0x63, 0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x73,
	0x5f, 0x72, 0x75, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09,
	0x69, 0x73, 0x52, 0x75, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x32, 0xc3, 0x04, 0x0a, 0x06, 0x4d, 0x69,
	0x6e, 0x69, 0x6f, 0x6e, 0x12, 0x3b, 0x0a, 0x04, 0x50, 0x69, 0x6e, 0x67, 0x12, 0x18, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4d, 0x69, 0x6e, 0x69, 0x6f, 0x6e, 0x50, 0x69, 0x6e, 0x67, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4d,
	0x69, 0x6e, 0x69, 0x6f, 0x6e, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x4d, 0x0a, 0x0a, 0x50, 0x72, 0x65, 0x70, 0x61, 0x72, 0x65, 0x4a, 0x6f, 0x62, 0x12,
	0x1e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4d, 0x69, 0x6e, 0x69, 0x6f, 0x6e, 0x50, 0x72,
	0x65, 0x70, 0x61, 0x72, 0x65, 0x4a, 0x6f, 0x62, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4d, 0x69, 0x6e, 0x69, 0x6f, 0x6e, 0x50, 0x72,
	0x65, 0x70, 0x61, 0x72, 0x65, 0x4a, 0x6f, 0x62, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x41, 0x0a, 0x06, 0x52, 0x75, 0x6e, 0x4a, 0x6f, 0x62, 0x12, 0x1a, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x4d, 0x69, 0x6e, 0x69, 0x6f, 0x6e, 0x52, 0x75, 0x6e, 0x4a, 0x6f, 0x62, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4d,
	0x69, 0x6e, 0x69, 0x6f, 0x6e, 0x52, 0x75, 0x6e, 0x4a, 0x6f, 0x62, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x44, 0x0a, 0x07, 0x53, 0x74, 0x6f, 0x70, 0x4a, 0x6f, 0x62, 0x12, 0x1b,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4d, 0x69, 0x6e, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x6f,
	0x70, 0x4a, 0x6f, 0x62, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x4d, 0x69, 0x6e, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x6f, 0x70, 0x4a, 0x6f,
	0x62, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5c, 0x0a, 0x0f, 0x47, 0x65, 0x74,
	0x44, 0x61, 0x74, 0x61, 0x53, 0x70, 0x65, 0x63, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x23, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4d, 0x69, 0x6e, 0x69, 0x6f, 0x6e, 0x47, 0x65, 0x74, 0x44, 0x61,
	0x74, 0x61, 0x53, 0x70, 0x65, 0x63, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x24, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4d, 0x69, 0x6e, 0x69, 0x6f, 0x6e,
	0x47, 0x65, 0x74, 0x44, 0x61, 0x74, 0x61, 0x53, 0x70, 0x65, 0x63, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x68, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x44, 0x42,
	0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x27,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4d, 0x69, 0x6e, 0x69, 0x6f, 0x6e, 0x47, 0x65, 0x74,
	0x44, 0x42, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x28, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x4d, 0x69, 0x6e, 0x69, 0x6f, 0x6e, 0x47, 0x65, 0x74, 0x44, 0x42, 0x43, 0x6f, 0x6e, 0x6e, 0x65,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x5c, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x57, 0x6f, 0x72, 0x6b, 0x6c, 0x6f, 0x61, 0x64,
	0x49, 0x6e, 0x66, 0x6f, 0x12, 0x23, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4d, 0x69, 0x6e,
	0x69, 0x6f, 0x6e, 0x47, 0x65, 0x74, 0x57, 0x6f, 0x72, 0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x4d, 0x69, 0x6e, 0x69, 0x6f, 0x6e, 0x47, 0x65, 0x74, 0x57, 0x6f, 0x72, 0x6b, 0x6c,
	0x6f, 0x61, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42,
	0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_diligent_minion_proto_rawDescOnce sync.Once
	file_diligent_minion_proto_rawDescData = file_diligent_minion_proto_rawDesc
)

func file_diligent_minion_proto_rawDescGZIP() []byte {
	file_diligent_minion_proto_rawDescOnce.Do(func() {
		file_diligent_minion_proto_rawDescData = protoimpl.X.CompressGZIP(file_diligent_minion_proto_rawDescData)
	})
	return file_diligent_minion_proto_rawDescData
}

var file_diligent_minion_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_diligent_minion_proto_goTypes = []interface{}{
	(*MinionPingRequest)(nil),                 // 0: proto.MinionPingRequest
	(*MinionPingResponse)(nil),                // 1: proto.MinionPingResponse
	(*MinionPrepareJobRequest)(nil),           // 2: proto.MinionPrepareJobRequest
	(*MinionPrepareJobResponse)(nil),          // 3: proto.MinionPrepareJobResponse
	(*MinionRunJobRequest)(nil),               // 4: proto.MinionRunJobRequest
	(*MinionRunJobResponse)(nil),              // 5: proto.MinionRunJobResponse
	(*MinionStopJobRequest)(nil),              // 6: proto.MinionStopJobRequest
	(*MinionStopJobResponse)(nil),             // 7: proto.MinionStopJobResponse
	(*MinionGetDataSpecInfoRequest)(nil),      // 8: proto.MinionGetDataSpecInfoRequest
	(*MinionGetDataSpecInfoResponse)(nil),     // 9: proto.MinionGetDataSpecInfoResponse
	(*MinionGetDBConnectionInfoRequest)(nil),  // 10: proto.MinionGetDBConnectionInfoRequest
	(*MinionGetDBConnectionInfoResponse)(nil), // 11: proto.MinionGetDBConnectionInfoResponse
	(*MinionGetWorkloadInfoRequest)(nil),      // 12: proto.MinionGetWorkloadInfoRequest
	(*MinionGetWorkloadInfoResponse)(nil),     // 13: proto.MinionGetWorkloadInfoResponse
	(*BuildInfo)(nil),                         // 14: proto.BuildInfo
	(*ProcessInfo)(nil),                       // 15: proto.ProcessInfo
	(*JobSpec)(nil),                           // 16: proto.JobSpec
	(*GeneralStatus)(nil),                     // 17: proto.GeneralStatus
	(*DataSpecInfo)(nil),                      // 18: proto.DataSpecInfo
	(*DBSpec)(nil),                            // 19: proto.DBSpec
	(*WorkloadSpec)(nil),                      // 20: proto.WorkloadSpec
}
var file_diligent_minion_proto_depIdxs = []int32{
	14, // 0: proto.MinionPingResponse.build_info:type_name -> proto.BuildInfo
	15, // 1: proto.MinionPingResponse.process_info:type_name -> proto.ProcessInfo
	16, // 2: proto.MinionPrepareJobRequest.job_spec:type_name -> proto.JobSpec
	17, // 3: proto.MinionPrepareJobResponse.status:type_name -> proto.GeneralStatus
	17, // 4: proto.MinionRunJobResponse.status:type_name -> proto.GeneralStatus
	17, // 5: proto.MinionStopJobResponse.status:type_name -> proto.GeneralStatus
	17, // 6: proto.MinionGetDataSpecInfoResponse.status:type_name -> proto.GeneralStatus
	18, // 7: proto.MinionGetDataSpecInfoResponse.data_spec_info:type_name -> proto.DataSpecInfo
	17, // 8: proto.MinionGetDBConnectionInfoResponse.status:type_name -> proto.GeneralStatus
	19, // 9: proto.MinionGetDBConnectionInfoResponse.db_spec:type_name -> proto.DBSpec
	17, // 10: proto.MinionGetWorkloadInfoResponse.status:type_name -> proto.GeneralStatus
	20, // 11: proto.MinionGetWorkloadInfoResponse.workload_spec:type_name -> proto.WorkloadSpec
	0,  // 12: proto.Minion.Ping:input_type -> proto.MinionPingRequest
	2,  // 13: proto.Minion.PrepareJob:input_type -> proto.MinionPrepareJobRequest
	4,  // 14: proto.Minion.RunJob:input_type -> proto.MinionRunJobRequest
	6,  // 15: proto.Minion.StopJob:input_type -> proto.MinionStopJobRequest
	8,  // 16: proto.Minion.GetDataSpecInfo:input_type -> proto.MinionGetDataSpecInfoRequest
	10, // 17: proto.Minion.GetDBConnectionInfo:input_type -> proto.MinionGetDBConnectionInfoRequest
	12, // 18: proto.Minion.GetWorkloadInfo:input_type -> proto.MinionGetWorkloadInfoRequest
	1,  // 19: proto.Minion.Ping:output_type -> proto.MinionPingResponse
	3,  // 20: proto.Minion.PrepareJob:output_type -> proto.MinionPrepareJobResponse
	5,  // 21: proto.Minion.RunJob:output_type -> proto.MinionRunJobResponse
	7,  // 22: proto.Minion.StopJob:output_type -> proto.MinionStopJobResponse
	9,  // 23: proto.Minion.GetDataSpecInfo:output_type -> proto.MinionGetDataSpecInfoResponse
	11, // 24: proto.Minion.GetDBConnectionInfo:output_type -> proto.MinionGetDBConnectionInfoResponse
	13, // 25: proto.Minion.GetWorkloadInfo:output_type -> proto.MinionGetWorkloadInfoResponse
	19, // [19:26] is the sub-list for method output_type
	12, // [12:19] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_diligent_minion_proto_init() }
func file_diligent_minion_proto_init() {
	if File_diligent_minion_proto != nil {
		return
	}
	file_diligent_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_diligent_minion_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MinionPingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_diligent_minion_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MinionPingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_diligent_minion_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MinionPrepareJobRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_diligent_minion_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MinionPrepareJobResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_diligent_minion_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MinionRunJobRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_diligent_minion_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MinionRunJobResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_diligent_minion_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MinionStopJobRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_diligent_minion_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MinionStopJobResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_diligent_minion_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MinionGetDataSpecInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_diligent_minion_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MinionGetDataSpecInfoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_diligent_minion_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MinionGetDBConnectionInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_diligent_minion_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MinionGetDBConnectionInfoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_diligent_minion_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MinionGetWorkloadInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_diligent_minion_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MinionGetWorkloadInfoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_diligent_minion_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_diligent_minion_proto_goTypes,
		DependencyIndexes: file_diligent_minion_proto_depIdxs,
		MessageInfos:      file_diligent_minion_proto_msgTypes,
	}.Build()
	File_diligent_minion_proto = out.File
	file_diligent_minion_proto_rawDesc = nil
	file_diligent_minion_proto_goTypes = nil
	file_diligent_minion_proto_depIdxs = nil
}
