// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: diligent.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nonce int32 `protobuf:"varint,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_diligent_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_diligent_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_diligent_proto_rawDescGZIP(), []int{0}
}

func (x *PingRequest) GetNonce() int32 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

type PingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nonce int32 `protobuf:"varint,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_diligent_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_diligent_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_diligent_proto_rawDescGZIP(), []int{1}
}

func (x *PingResponse) GetNonce() int32 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

type DataSpec struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SpecType       string      `protobuf:"bytes,1,opt,name=spec_type,json=specType,proto3" json:"spec_type,omitempty"`
	Version        int32       `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	RecordSize     int32       `protobuf:"varint,3,opt,name=record_size,json=recordSize,proto3" json:"record_size,omitempty"`
	KeyGenSpec     *KeyGenSpec `protobuf:"bytes,4,opt,name=key_gen_spec,json=keyGenSpec,proto3" json:"key_gen_spec,omitempty"`
	UniqTrSpec     *TrSpec     `protobuf:"bytes,5,opt,name=uniq_tr_spec,json=uniqTrSpec,proto3" json:"uniq_tr_spec,omitempty"`
	SmallGrpTrSpec *TrSpec     `protobuf:"bytes,6,opt,name=small_grp_tr_spec,json=smallGrpTrSpec,proto3" json:"small_grp_tr_spec,omitempty"`
	LargeGrpTrSpec *TrSpec     `protobuf:"bytes,7,opt,name=large_grp_tr_spec,json=largeGrpTrSpec,proto3" json:"large_grp_tr_spec,omitempty"`
	FixedValue     string      `protobuf:"bytes,8,opt,name=fixed_value,json=fixedValue,proto3" json:"fixed_value,omitempty"`
}

func (x *DataSpec) Reset() {
	*x = DataSpec{}
	if protoimpl.UnsafeEnabled {
		mi := &file_diligent_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataSpec) ProtoMessage() {}

func (x *DataSpec) ProtoReflect() protoreflect.Message {
	mi := &file_diligent_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataSpec.ProtoReflect.Descriptor instead.
func (*DataSpec) Descriptor() ([]byte, []int) {
	return file_diligent_proto_rawDescGZIP(), []int{2}
}

func (x *DataSpec) GetSpecType() string {
	if x != nil {
		return x.SpecType
	}
	return ""
}

func (x *DataSpec) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *DataSpec) GetRecordSize() int32 {
	if x != nil {
		return x.RecordSize
	}
	return 0
}

func (x *DataSpec) GetKeyGenSpec() *KeyGenSpec {
	if x != nil {
		return x.KeyGenSpec
	}
	return nil
}

func (x *DataSpec) GetUniqTrSpec() *TrSpec {
	if x != nil {
		return x.UniqTrSpec
	}
	return nil
}

func (x *DataSpec) GetSmallGrpTrSpec() *TrSpec {
	if x != nil {
		return x.SmallGrpTrSpec
	}
	return nil
}

func (x *DataSpec) GetLargeGrpTrSpec() *TrSpec {
	if x != nil {
		return x.LargeGrpTrSpec
	}
	return nil
}

func (x *DataSpec) GetFixedValue() string {
	if x != nil {
		return x.FixedValue
	}
	return ""
}

type KeyGenSpec struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LevelSizes []int32  `protobuf:"varint,1,rep,packed,name=level_sizes,json=levelSizes,proto3" json:"level_sizes,omitempty"`
	SubKeys    []string `protobuf:"bytes,2,rep,name=sub_keys,json=subKeys,proto3" json:"sub_keys,omitempty"`
	Delim      string   `protobuf:"bytes,3,opt,name=delim,proto3" json:"delim,omitempty"`
}

func (x *KeyGenSpec) Reset() {
	*x = KeyGenSpec{}
	if protoimpl.UnsafeEnabled {
		mi := &file_diligent_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeyGenSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyGenSpec) ProtoMessage() {}

func (x *KeyGenSpec) ProtoReflect() protoreflect.Message {
	mi := &file_diligent_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyGenSpec.ProtoReflect.Descriptor instead.
func (*KeyGenSpec) Descriptor() ([]byte, []int) {
	return file_diligent_proto_rawDescGZIP(), []int{3}
}

func (x *KeyGenSpec) GetLevelSizes() []int32 {
	if x != nil {
		return x.LevelSizes
	}
	return nil
}

func (x *KeyGenSpec) GetSubKeys() []string {
	if x != nil {
		return x.SubKeys
	}
	return nil
}

func (x *KeyGenSpec) GetDelim() string {
	if x != nil {
		return x.Delim
	}
	return ""
}

type TrSpec struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Inputs       string `protobuf:"bytes,1,opt,name=inputs,proto3" json:"inputs,omitempty"`
	Replacements string `protobuf:"bytes,2,opt,name=replacements,proto3" json:"replacements,omitempty"`
}

func (x *TrSpec) Reset() {
	*x = TrSpec{}
	if protoimpl.UnsafeEnabled {
		mi := &file_diligent_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TrSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrSpec) ProtoMessage() {}

func (x *TrSpec) ProtoReflect() protoreflect.Message {
	mi := &file_diligent_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrSpec.ProtoReflect.Descriptor instead.
func (*TrSpec) Descriptor() ([]byte, []int) {
	return file_diligent_proto_rawDescGZIP(), []int{4}
}

func (x *TrSpec) GetInputs() string {
	if x != nil {
		return x.Inputs
	}
	return ""
}

func (x *TrSpec) GetReplacements() string {
	if x != nil {
		return x.Replacements
	}
	return ""
}

type DataSpecInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SpecName   string `protobuf:"bytes,1,opt,name=spec_name,json=specName,proto3" json:"spec_name,omitempty"`
	SpecType   string `protobuf:"bytes,2,opt,name=spec_type,json=specType,proto3" json:"spec_type,omitempty"`
	Version    int32  `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	NumRecs    int32  `protobuf:"varint,4,opt,name=num_recs,json=numRecs,proto3" json:"num_recs,omitempty"`
	RecordSize int32  `protobuf:"varint,5,opt,name=record_size,json=recordSize,proto3" json:"record_size,omitempty"`
	Hash       int32  `protobuf:"varint,6,opt,name=hash,proto3" json:"hash,omitempty"`
}

func (x *DataSpecInfo) Reset() {
	*x = DataSpecInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_diligent_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataSpecInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataSpecInfo) ProtoMessage() {}

func (x *DataSpecInfo) ProtoReflect() protoreflect.Message {
	mi := &file_diligent_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataSpecInfo.ProtoReflect.Descriptor instead.
func (*DataSpecInfo) Descriptor() ([]byte, []int) {
	return file_diligent_proto_rawDescGZIP(), []int{5}
}

func (x *DataSpecInfo) GetSpecName() string {
	if x != nil {
		return x.SpecName
	}
	return ""
}

func (x *DataSpecInfo) GetSpecType() string {
	if x != nil {
		return x.SpecType
	}
	return ""
}

func (x *DataSpecInfo) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *DataSpecInfo) GetNumRecs() int32 {
	if x != nil {
		return x.NumRecs
	}
	return 0
}

func (x *DataSpecInfo) GetRecordSize() int32 {
	if x != nil {
		return x.RecordSize
	}
	return 0
}

func (x *DataSpecInfo) GetHash() int32 {
	if x != nil {
		return x.Hash
	}
	return 0
}

type LoadDataSpecRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SpecName string    `protobuf:"bytes,1,opt,name=spec_name,json=specName,proto3" json:"spec_name,omitempty"`
	DataSpec *DataSpec `protobuf:"bytes,2,opt,name=data_spec,json=dataSpec,proto3" json:"data_spec,omitempty"`
	Hash     int32     `protobuf:"varint,3,opt,name=hash,proto3" json:"hash,omitempty"`
}

func (x *LoadDataSpecRequest) Reset() {
	*x = LoadDataSpecRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_diligent_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoadDataSpecRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadDataSpecRequest) ProtoMessage() {}

func (x *LoadDataSpecRequest) ProtoReflect() protoreflect.Message {
	mi := &file_diligent_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadDataSpecRequest.ProtoReflect.Descriptor instead.
func (*LoadDataSpecRequest) Descriptor() ([]byte, []int) {
	return file_diligent_proto_rawDescGZIP(), []int{6}
}

func (x *LoadDataSpecRequest) GetSpecName() string {
	if x != nil {
		return x.SpecName
	}
	return ""
}

func (x *LoadDataSpecRequest) GetDataSpec() *DataSpec {
	if x != nil {
		return x.DataSpec
	}
	return nil
}

func (x *LoadDataSpecRequest) GetHash() int32 {
	if x != nil {
		return x.Hash
	}
	return 0
}

type LoadDataSpecResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsOk          bool          `protobuf:"varint,1,opt,name=is_ok,json=isOk,proto3" json:"is_ok,omitempty"`
	FailureReason string        `protobuf:"bytes,2,opt,name=failure_reason,json=failureReason,proto3" json:"failure_reason,omitempty"`
	DataSpecInfo  *DataSpecInfo `protobuf:"bytes,3,opt,name=data_spec_info,json=dataSpecInfo,proto3" json:"data_spec_info,omitempty"`
}

func (x *LoadDataSpecResponse) Reset() {
	*x = LoadDataSpecResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_diligent_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoadDataSpecResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadDataSpecResponse) ProtoMessage() {}

func (x *LoadDataSpecResponse) ProtoReflect() protoreflect.Message {
	mi := &file_diligent_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadDataSpecResponse.ProtoReflect.Descriptor instead.
func (*LoadDataSpecResponse) Descriptor() ([]byte, []int) {
	return file_diligent_proto_rawDescGZIP(), []int{7}
}

func (x *LoadDataSpecResponse) GetIsOk() bool {
	if x != nil {
		return x.IsOk
	}
	return false
}

func (x *LoadDataSpecResponse) GetFailureReason() string {
	if x != nil {
		return x.FailureReason
	}
	return ""
}

func (x *LoadDataSpecResponse) GetDataSpecInfo() *DataSpecInfo {
	if x != nil {
		return x.DataSpecInfo
	}
	return nil
}

type GetDataSpecInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetDataSpecInfoRequest) Reset() {
	*x = GetDataSpecInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_diligent_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDataSpecInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDataSpecInfoRequest) ProtoMessage() {}

func (x *GetDataSpecInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_diligent_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDataSpecInfoRequest.ProtoReflect.Descriptor instead.
func (*GetDataSpecInfoRequest) Descriptor() ([]byte, []int) {
	return file_diligent_proto_rawDescGZIP(), []int{8}
}

type GetDataSpecInfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsOk          bool          `protobuf:"varint,1,opt,name=is_ok,json=isOk,proto3" json:"is_ok,omitempty"`
	FailureReason string        `protobuf:"bytes,2,opt,name=failure_reason,json=failureReason,proto3" json:"failure_reason,omitempty"`
	DataSpecInfo  *DataSpecInfo `protobuf:"bytes,3,opt,name=data_spec_info,json=dataSpecInfo,proto3" json:"data_spec_info,omitempty"`
}

func (x *GetDataSpecInfoResponse) Reset() {
	*x = GetDataSpecInfoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_diligent_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDataSpecInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDataSpecInfoResponse) ProtoMessage() {}

func (x *GetDataSpecInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_diligent_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDataSpecInfoResponse.ProtoReflect.Descriptor instead.
func (*GetDataSpecInfoResponse) Descriptor() ([]byte, []int) {
	return file_diligent_proto_rawDescGZIP(), []int{9}
}

func (x *GetDataSpecInfoResponse) GetIsOk() bool {
	if x != nil {
		return x.IsOk
	}
	return false
}

func (x *GetDataSpecInfoResponse) GetFailureReason() string {
	if x != nil {
		return x.FailureReason
	}
	return ""
}

func (x *GetDataSpecInfoResponse) GetDataSpecInfo() *DataSpecInfo {
	if x != nil {
		return x.DataSpecInfo
	}
	return nil
}

type OpenDBConnectionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Driver string `protobuf:"bytes,1,opt,name=driver,proto3" json:"driver,omitempty"`
	Url    string `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *OpenDBConnectionRequest) Reset() {
	*x = OpenDBConnectionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_diligent_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OpenDBConnectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenDBConnectionRequest) ProtoMessage() {}

func (x *OpenDBConnectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_diligent_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenDBConnectionRequest.ProtoReflect.Descriptor instead.
func (*OpenDBConnectionRequest) Descriptor() ([]byte, []int) {
	return file_diligent_proto_rawDescGZIP(), []int{10}
}

func (x *OpenDBConnectionRequest) GetDriver() string {
	if x != nil {
		return x.Driver
	}
	return ""
}

func (x *OpenDBConnectionRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type OpenDBConnectionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsOk          bool   `protobuf:"varint,1,opt,name=is_ok,json=isOk,proto3" json:"is_ok,omitempty"`
	FailureReason string `protobuf:"bytes,2,opt,name=failure_reason,json=failureReason,proto3" json:"failure_reason,omitempty"`
}

func (x *OpenDBConnectionResponse) Reset() {
	*x = OpenDBConnectionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_diligent_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OpenDBConnectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenDBConnectionResponse) ProtoMessage() {}

func (x *OpenDBConnectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_diligent_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenDBConnectionResponse.ProtoReflect.Descriptor instead.
func (*OpenDBConnectionResponse) Descriptor() ([]byte, []int) {
	return file_diligent_proto_rawDescGZIP(), []int{11}
}

func (x *OpenDBConnectionResponse) GetIsOk() bool {
	if x != nil {
		return x.IsOk
	}
	return false
}

func (x *OpenDBConnectionResponse) GetFailureReason() string {
	if x != nil {
		return x.FailureReason
	}
	return ""
}

type GetDBConnectionInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetDBConnectionInfoRequest) Reset() {
	*x = GetDBConnectionInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_diligent_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDBConnectionInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDBConnectionInfoRequest) ProtoMessage() {}

func (x *GetDBConnectionInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_diligent_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDBConnectionInfoRequest.ProtoReflect.Descriptor instead.
func (*GetDBConnectionInfoRequest) Descriptor() ([]byte, []int) {
	return file_diligent_proto_rawDescGZIP(), []int{12}
}

type GetDBConnectionInfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsOk          bool   `protobuf:"varint,1,opt,name=is_ok,json=isOk,proto3" json:"is_ok,omitempty"`
	FailureReason string `protobuf:"bytes,2,opt,name=failure_reason,json=failureReason,proto3" json:"failure_reason,omitempty"`
	Driver        string `protobuf:"bytes,3,opt,name=driver,proto3" json:"driver,omitempty"`
	Url           string `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *GetDBConnectionInfoResponse) Reset() {
	*x = GetDBConnectionInfoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_diligent_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDBConnectionInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDBConnectionInfoResponse) ProtoMessage() {}

func (x *GetDBConnectionInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_diligent_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDBConnectionInfoResponse.ProtoReflect.Descriptor instead.
func (*GetDBConnectionInfoResponse) Descriptor() ([]byte, []int) {
	return file_diligent_proto_rawDescGZIP(), []int{13}
}

func (x *GetDBConnectionInfoResponse) GetIsOk() bool {
	if x != nil {
		return x.IsOk
	}
	return false
}

func (x *GetDBConnectionInfoResponse) GetFailureReason() string {
	if x != nil {
		return x.FailureReason
	}
	return ""
}

func (x *GetDBConnectionInfoResponse) GetDriver() string {
	if x != nil {
		return x.Driver
	}
	return ""
}

func (x *GetDBConnectionInfoResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type CloseDBConnectionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CloseDBConnectionRequest) Reset() {
	*x = CloseDBConnectionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_diligent_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CloseDBConnectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseDBConnectionRequest) ProtoMessage() {}

func (x *CloseDBConnectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_diligent_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseDBConnectionRequest.ProtoReflect.Descriptor instead.
func (*CloseDBConnectionRequest) Descriptor() ([]byte, []int) {
	return file_diligent_proto_rawDescGZIP(), []int{14}
}

type CloseDBConnectionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsOk          bool   `protobuf:"varint,1,opt,name=is_ok,json=isOk,proto3" json:"is_ok,omitempty"`
	FailureReason string `protobuf:"bytes,2,opt,name=failure_reason,json=failureReason,proto3" json:"failure_reason,omitempty"`
}

func (x *CloseDBConnectionResponse) Reset() {
	*x = CloseDBConnectionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_diligent_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CloseDBConnectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseDBConnectionResponse) ProtoMessage() {}

func (x *CloseDBConnectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_diligent_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseDBConnectionResponse.ProtoReflect.Descriptor instead.
func (*CloseDBConnectionResponse) Descriptor() ([]byte, []int) {
	return file_diligent_proto_rawDescGZIP(), []int{15}
}

func (x *CloseDBConnectionResponse) GetIsOk() bool {
	if x != nil {
		return x.IsOk
	}
	return false
}

func (x *CloseDBConnectionResponse) GetFailureReason() string {
	if x != nil {
		return x.FailureReason
	}
	return ""
}

type RunWorkloadRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WorkloadName  string `protobuf:"bytes,1,opt,name=workload_name,json=workloadName,proto3" json:"workload_name,omitempty"`
	AssignedRange *Range `protobuf:"bytes,2,opt,name=assigned_range,json=assignedRange,proto3" json:"assigned_range,omitempty"`
	TableName     string `protobuf:"bytes,3,opt,name=table_name,json=tableName,proto3" json:"table_name,omitempty"`
	DurationSec   int32  `protobuf:"varint,4,opt,name=duration_sec,json=durationSec,proto3" json:"duration_sec,omitempty"`
	Concurrency   int32  `protobuf:"varint,5,opt,name=concurrency,proto3" json:"concurrency,omitempty"`
	BatchSize     int32  `protobuf:"varint,6,opt,name=batch_size,json=batchSize,proto3" json:"batch_size,omitempty"`
}

func (x *RunWorkloadRequest) Reset() {
	*x = RunWorkloadRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_diligent_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RunWorkloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunWorkloadRequest) ProtoMessage() {}

func (x *RunWorkloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_diligent_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunWorkloadRequest.ProtoReflect.Descriptor instead.
func (*RunWorkloadRequest) Descriptor() ([]byte, []int) {
	return file_diligent_proto_rawDescGZIP(), []int{16}
}

func (x *RunWorkloadRequest) GetWorkloadName() string {
	if x != nil {
		return x.WorkloadName
	}
	return ""
}

func (x *RunWorkloadRequest) GetAssignedRange() *Range {
	if x != nil {
		return x.AssignedRange
	}
	return nil
}

func (x *RunWorkloadRequest) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

func (x *RunWorkloadRequest) GetDurationSec() int32 {
	if x != nil {
		return x.DurationSec
	}
	return 0
}

func (x *RunWorkloadRequest) GetConcurrency() int32 {
	if x != nil {
		return x.Concurrency
	}
	return 0
}

func (x *RunWorkloadRequest) GetBatchSize() int32 {
	if x != nil {
		return x.BatchSize
	}
	return 0
}

type Range struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Start int32 `protobuf:"varint,1,opt,name=start,proto3" json:"start,omitempty"`
	Limit int32 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *Range) Reset() {
	*x = Range{}
	if protoimpl.UnsafeEnabled {
		mi := &file_diligent_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Range) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Range) ProtoMessage() {}

func (x *Range) ProtoReflect() protoreflect.Message {
	mi := &file_diligent_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Range.ProtoReflect.Descriptor instead.
func (*Range) Descriptor() ([]byte, []int) {
	return file_diligent_proto_rawDescGZIP(), []int{17}
}

func (x *Range) GetStart() int32 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *Range) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type RunWorkloadResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsOk          bool   `protobuf:"varint,1,opt,name=is_ok,json=isOk,proto3" json:"is_ok,omitempty"`
	FailureReason string `protobuf:"bytes,2,opt,name=failure_reason,json=failureReason,proto3" json:"failure_reason,omitempty"`
}

func (x *RunWorkloadResponse) Reset() {
	*x = RunWorkloadResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_diligent_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RunWorkloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunWorkloadResponse) ProtoMessage() {}

func (x *RunWorkloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_diligent_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunWorkloadResponse.ProtoReflect.Descriptor instead.
func (*RunWorkloadResponse) Descriptor() ([]byte, []int) {
	return file_diligent_proto_rawDescGZIP(), []int{18}
}

func (x *RunWorkloadResponse) GetIsOk() bool {
	if x != nil {
		return x.IsOk
	}
	return false
}

func (x *RunWorkloadResponse) GetFailureReason() string {
	if x != nil {
		return x.FailureReason
	}
	return ""
}

type GetWorkloadInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetWorkloadInfoRequest) Reset() {
	*x = GetWorkloadInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_diligent_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetWorkloadInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkloadInfoRequest) ProtoMessage() {}

func (x *GetWorkloadInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_diligent_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkloadInfoRequest.ProtoReflect.Descriptor instead.
func (*GetWorkloadInfoRequest) Descriptor() ([]byte, []int) {
	return file_diligent_proto_rawDescGZIP(), []int{19}
}

type GetWorkloadInfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsOk          bool          `protobuf:"varint,1,opt,name=is_ok,json=isOk,proto3" json:"is_ok,omitempty"`
	FailureReason string        `protobuf:"bytes,2,opt,name=failure_reason,json=failureReason,proto3" json:"failure_reason,omitempty"`
	WorkloadInfo  *WorkloadInfo `protobuf:"bytes,3,opt,name=workload_info,json=workloadInfo,proto3" json:"workload_info,omitempty"`
}

func (x *GetWorkloadInfoResponse) Reset() {
	*x = GetWorkloadInfoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_diligent_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetWorkloadInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkloadInfoResponse) ProtoMessage() {}

func (x *GetWorkloadInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_diligent_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkloadInfoResponse.ProtoReflect.Descriptor instead.
func (*GetWorkloadInfoResponse) Descriptor() ([]byte, []int) {
	return file_diligent_proto_rawDescGZIP(), []int{20}
}

func (x *GetWorkloadInfoResponse) GetIsOk() bool {
	if x != nil {
		return x.IsOk
	}
	return false
}

func (x *GetWorkloadInfoResponse) GetFailureReason() string {
	if x != nil {
		return x.FailureReason
	}
	return ""
}

func (x *GetWorkloadInfoResponse) GetWorkloadInfo() *WorkloadInfo {
	if x != nil {
		return x.WorkloadInfo
	}
	return nil
}

type WorkloadInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WorkloadName  string `protobuf:"bytes,1,opt,name=workload_name,json=workloadName,proto3" json:"workload_name,omitempty"`
	AssignedRange *Range `protobuf:"bytes,2,opt,name=assigned_range,json=assignedRange,proto3" json:"assigned_range,omitempty"`
	TableName     string `protobuf:"bytes,3,opt,name=table_name,json=tableName,proto3" json:"table_name,omitempty"`
	DurationSec   int32  `protobuf:"varint,4,opt,name=duration_sec,json=durationSec,proto3" json:"duration_sec,omitempty"`
	Concurrency   int32  `protobuf:"varint,5,opt,name=concurrency,proto3" json:"concurrency,omitempty"`
	BatchSize     int32  `protobuf:"varint,6,opt,name=batch_size,json=batchSize,proto3" json:"batch_size,omitempty"`
	IsRunning     bool   `protobuf:"varint,7,opt,name=isRunning,proto3" json:"isRunning,omitempty"`
}

func (x *WorkloadInfo) Reset() {
	*x = WorkloadInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_diligent_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WorkloadInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkloadInfo) ProtoMessage() {}

func (x *WorkloadInfo) ProtoReflect() protoreflect.Message {
	mi := &file_diligent_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkloadInfo.ProtoReflect.Descriptor instead.
func (*WorkloadInfo) Descriptor() ([]byte, []int) {
	return file_diligent_proto_rawDescGZIP(), []int{21}
}

func (x *WorkloadInfo) GetWorkloadName() string {
	if x != nil {
		return x.WorkloadName
	}
	return ""
}

func (x *WorkloadInfo) GetAssignedRange() *Range {
	if x != nil {
		return x.AssignedRange
	}
	return nil
}

func (x *WorkloadInfo) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

func (x *WorkloadInfo) GetDurationSec() int32 {
	if x != nil {
		return x.DurationSec
	}
	return 0
}

func (x *WorkloadInfo) GetConcurrency() int32 {
	if x != nil {
		return x.Concurrency
	}
	return 0
}

func (x *WorkloadInfo) GetBatchSize() int32 {
	if x != nil {
		return x.BatchSize
	}
	return 0
}

func (x *WorkloadInfo) GetIsRunning() bool {
	if x != nil {
		return x.IsRunning
	}
	return false
}

type StopWorkloadRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StopWorkloadRequest) Reset() {
	*x = StopWorkloadRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_diligent_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StopWorkloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopWorkloadRequest) ProtoMessage() {}

func (x *StopWorkloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_diligent_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopWorkloadRequest.ProtoReflect.Descriptor instead.
func (*StopWorkloadRequest) Descriptor() ([]byte, []int) {
	return file_diligent_proto_rawDescGZIP(), []int{22}
}

type StopWorkloadResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsOk          bool   `protobuf:"varint,1,opt,name=is_ok,json=isOk,proto3" json:"is_ok,omitempty"`
	FailureReason string `protobuf:"bytes,2,opt,name=failure_reason,json=failureReason,proto3" json:"failure_reason,omitempty"`
}

func (x *StopWorkloadResponse) Reset() {
	*x = StopWorkloadResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_diligent_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StopWorkloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopWorkloadResponse) ProtoMessage() {}

func (x *StopWorkloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_diligent_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopWorkloadResponse.ProtoReflect.Descriptor instead.
func (*StopWorkloadResponse) Descriptor() ([]byte, []int) {
	return file_diligent_proto_rawDescGZIP(), []int{23}
}

func (x *StopWorkloadResponse) GetIsOk() bool {
	if x != nil {
		return x.IsOk
	}
	return false
}

func (x *StopWorkloadResponse) GetFailureReason() string {
	if x != nil {
		return x.FailureReason
	}
	return ""
}

var File_diligent_proto protoreflect.FileDescriptor

var file_diligent_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x64, 0x69, 0x6c, 0x69, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x23, 0x0a, 0x0b, 0x50, 0x69, 0x6e, 0x67, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x22, 0x24, 0x0a, 0x0c,
	0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6e, 0x6f, 0x6e,
	0x63, 0x65, 0x22, 0xdd, 0x02, 0x0a, 0x08, 0x44, 0x61, 0x74, 0x61, 0x53, 0x70, 0x65, 0x63, 0x12,
	0x1b, 0x0a, 0x09, 0x73, 0x70, 0x65, 0x63, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x73, 0x70, 0x65, 0x63, 0x54, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x76,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1f, 0x0a, 0x0b, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64,
	0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x72, 0x65, 0x63,
	0x6f, 0x72, 0x64, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x33, 0x0a, 0x0c, 0x6b, 0x65, 0x79, 0x5f, 0x67,
	0x65, 0x6e, 0x5f, 0x73, 0x70, 0x65, 0x63, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4b, 0x65, 0x79, 0x47, 0x65, 0x6e, 0x53, 0x70, 0x65, 0x63,
	0x52, 0x0a, 0x6b, 0x65, 0x79, 0x47, 0x65, 0x6e, 0x53, 0x70, 0x65, 0x63, 0x12, 0x2f, 0x0a, 0x0c,
	0x75, 0x6e, 0x69, 0x71, 0x5f, 0x74, 0x72, 0x5f, 0x73, 0x70, 0x65, 0x63, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x72, 0x53, 0x70, 0x65,
	0x63, 0x52, 0x0a, 0x75, 0x6e, 0x69, 0x71, 0x54, 0x72, 0x53, 0x70, 0x65, 0x63, 0x12, 0x38, 0x0a,
	0x11, 0x73, 0x6d, 0x61, 0x6c, 0x6c, 0x5f, 0x67, 0x72, 0x70, 0x5f, 0x74, 0x72, 0x5f, 0x73, 0x70,
	0x65, 0x63, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x54, 0x72, 0x53, 0x70, 0x65, 0x63, 0x52, 0x0e, 0x73, 0x6d, 0x61, 0x6c, 0x6c, 0x47, 0x72,
	0x70, 0x54, 0x72, 0x53, 0x70, 0x65, 0x63, 0x12, 0x38, 0x0a, 0x11, 0x6c, 0x61, 0x72, 0x67, 0x65,
	0x5f, 0x67, 0x72, 0x70, 0x5f, 0x74, 0x72, 0x5f, 0x73, 0x70, 0x65, 0x63, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x72, 0x53, 0x70, 0x65,
	0x63, 0x52, 0x0e, 0x6c, 0x61, 0x72, 0x67, 0x65, 0x47, 0x72, 0x70, 0x54, 0x72, 0x53, 0x70, 0x65,
	0x63, 0x12, 0x1f, 0x0a, 0x0b, 0x66, 0x69, 0x78, 0x65, 0x64, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x66, 0x69, 0x78, 0x65, 0x64, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x22, 0x5e, 0x0a, 0x0a, 0x4b, 0x65, 0x79, 0x47, 0x65, 0x6e, 0x53, 0x70, 0x65, 0x63,
	0x12, 0x1f, 0x0a, 0x0b, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x05, 0x52, 0x0a, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x53, 0x69, 0x7a, 0x65,
	0x73, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x75, 0x62, 0x5f, 0x6b, 0x65, 0x79, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x07, 0x73, 0x75, 0x62, 0x4b, 0x65, 0x79, 0x73, 0x12, 0x14, 0x0a, 0x05,
	0x64, 0x65, 0x6c, 0x69, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x64, 0x65, 0x6c,
	0x69, 0x6d, 0x22, 0x44, 0x0a, 0x06, 0x54, 0x72, 0x53, 0x70, 0x65, 0x63, 0x12, 0x16, 0x0a, 0x06,
	0x69, 0x6e, 0x70, 0x75, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x69, 0x6e,
	0x70, 0x75, 0x74, 0x73, 0x12, 0x22, 0x0a, 0x0c, 0x72, 0x65, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x6d,
	0x65, 0x6e, 0x74, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x72, 0x65, 0x70, 0x6c,
	0x61, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x22, 0xb2, 0x01, 0x0a, 0x0c, 0x44, 0x61, 0x74,
	0x61, 0x53, 0x70, 0x65, 0x63, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x70, 0x65,
	0x63, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x70,
	0x65, 0x63, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x70, 0x65, 0x63, 0x5f, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x70, 0x65, 0x63, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x19, 0x0a,
	0x08, 0x6e, 0x75, 0x6d, 0x5f, 0x72, 0x65, 0x63, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x07, 0x6e, 0x75, 0x6d, 0x52, 0x65, 0x63, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x72, 0x65, 0x63, 0x6f,
	0x72, 0x64, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x72,
	0x65, 0x63, 0x6f, 0x72, 0x64, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x61, 0x73,
	0x68, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x68, 0x61, 0x73, 0x68, 0x22, 0x74, 0x0a,
	0x13, 0x4c, 0x6f, 0x61, 0x64, 0x44, 0x61, 0x74, 0x61, 0x53, 0x70, 0x65, 0x63, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x70, 0x65, 0x63, 0x5f, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x70, 0x65, 0x63, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x2c, 0x0a, 0x09, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x73, 0x70, 0x65, 0x63, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x61, 0x74,
	0x61, 0x53, 0x70, 0x65, 0x63, 0x52, 0x08, 0x64, 0x61, 0x74, 0x61, 0x53, 0x70, 0x65, 0x63, 0x12,
	0x12, 0x0a, 0x04, 0x68, 0x61, 0x73, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x68,
	0x61, 0x73, 0x68, 0x22, 0x8d, 0x01, 0x0a, 0x14, 0x4c, 0x6f, 0x61, 0x64, 0x44, 0x61, 0x74, 0x61,
	0x53, 0x70, 0x65, 0x63, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x13, 0x0a, 0x05,
	0x69, 0x73, 0x5f, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x69, 0x73, 0x4f,
	0x6b, 0x12, 0x25, 0x0a, 0x0e, 0x66, 0x61, 0x69, 0x6c, 0x75, 0x72, 0x65, 0x5f, 0x72, 0x65, 0x61,
	0x73, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x66, 0x61, 0x69, 0x6c, 0x75,
	0x72, 0x65, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12, 0x39, 0x0a, 0x0e, 0x64, 0x61, 0x74, 0x61,
	0x5f, 0x73, 0x70, 0x65, 0x63, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x53, 0x70, 0x65,
	0x63, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0c, 0x64, 0x61, 0x74, 0x61, 0x53, 0x70, 0x65, 0x63, 0x49,
	0x6e, 0x66, 0x6f, 0x22, 0x18, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x44, 0x61, 0x74, 0x61, 0x53, 0x70,
	0x65, 0x63, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x90, 0x01,
	0x0a, 0x17, 0x47, 0x65, 0x74, 0x44, 0x61, 0x74, 0x61, 0x53, 0x70, 0x65, 0x63, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x13, 0x0a, 0x05, 0x69, 0x73, 0x5f,
	0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x69, 0x73, 0x4f, 0x6b, 0x12, 0x25,
	0x0a, 0x0e, 0x66, 0x61, 0x69, 0x6c, 0x75, 0x72, 0x65, 0x5f, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x66, 0x61, 0x69, 0x6c, 0x75, 0x72, 0x65, 0x52,
	0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12, 0x39, 0x0a, 0x0e, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x73, 0x70,
	0x65, 0x63, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x53, 0x70, 0x65, 0x63, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x0c, 0x64, 0x61, 0x74, 0x61, 0x53, 0x70, 0x65, 0x63, 0x49, 0x6e, 0x66, 0x6f,
	0x22, 0x43, 0x0a, 0x17, 0x4f, 0x70, 0x65, 0x6e, 0x44, 0x42, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x64,
	0x72, 0x69, 0x76, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x72, 0x69,
	0x76, 0x65, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x75, 0x72, 0x6c, 0x22, 0x56, 0x0a, 0x18, 0x4f, 0x70, 0x65, 0x6e, 0x44, 0x42, 0x43,
	0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x13, 0x0a, 0x05, 0x69, 0x73, 0x5f, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x04, 0x69, 0x73, 0x4f, 0x6b, 0x12, 0x25, 0x0a, 0x0e, 0x66, 0x61, 0x69, 0x6c, 0x75, 0x72,
	0x65, 0x5f, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d,
	0x66, 0x61, 0x69, 0x6c, 0x75, 0x72, 0x65, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x22, 0x1c, 0x0a,
	0x1a, 0x47, 0x65, 0x74, 0x44, 0x42, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x83, 0x01, 0x0a, 0x1b,
	0x47, 0x65, 0x74, 0x44, 0x42, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x13, 0x0a, 0x05, 0x69,
	0x73, 0x5f, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x69, 0x73, 0x4f, 0x6b,
	0x12, 0x25, 0x0a, 0x0e, 0x66, 0x61, 0x69, 0x6c, 0x75, 0x72, 0x65, 0x5f, 0x72, 0x65, 0x61, 0x73,
	0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x66, 0x61, 0x69, 0x6c, 0x75, 0x72,
	0x65, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x72, 0x69, 0x76, 0x65,
	0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x72, 0x69, 0x76, 0x65, 0x72, 0x12,
	0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72,
	0x6c, 0x22, 0x1a, 0x0a, 0x18, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x44, 0x42, 0x43, 0x6f, 0x6e, 0x6e,
	0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x57, 0x0a,
	0x19, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x44, 0x42, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x13, 0x0a, 0x05, 0x69, 0x73,
	0x5f, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x69, 0x73, 0x4f, 0x6b, 0x12,
	0x25, 0x0a, 0x0e, 0x66, 0x61, 0x69, 0x6c, 0x75, 0x72, 0x65, 0x5f, 0x72, 0x65, 0x61, 0x73, 0x6f,
	0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x66, 0x61, 0x69, 0x6c, 0x75, 0x72, 0x65,
	0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x22, 0xf1, 0x01, 0x0a, 0x12, 0x52, 0x75, 0x6e, 0x57, 0x6f,
	0x72, 0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x23, 0x0a,
	0x0d, 0x77, 0x6f, 0x72, 0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x77, 0x6f, 0x72, 0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x33, 0x0a, 0x0e, 0x61, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x5f, 0x72,
	0x61, 0x6e, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x0d, 0x61, 0x73, 0x73, 0x69, 0x67, 0x6e,
	0x65, 0x64, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x61, 0x62, 0x6c, 0x65,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x61, 0x62,
	0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x5f, 0x73, 0x65, 0x63, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x64, 0x75,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x63, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x6f, 0x6e,
	0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b,
	0x63, 0x6f, 0x6e, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x12, 0x1d, 0x0a, 0x0a, 0x62,
	0x61, 0x74, 0x63, 0x68, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x09, 0x62, 0x61, 0x74, 0x63, 0x68, 0x53, 0x69, 0x7a, 0x65, 0x22, 0x33, 0x0a, 0x05, 0x52, 0x61,
	0x6e, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d,
	0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x22,
	0x51, 0x0a, 0x13, 0x52, 0x75, 0x6e, 0x57, 0x6f, 0x72, 0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x13, 0x0a, 0x05, 0x69, 0x73, 0x5f, 0x6f, 0x6b, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x69, 0x73, 0x4f, 0x6b, 0x12, 0x25, 0x0a, 0x0e, 0x66,
	0x61, 0x69, 0x6c, 0x75, 0x72, 0x65, 0x5f, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0d, 0x66, 0x61, 0x69, 0x6c, 0x75, 0x72, 0x65, 0x52, 0x65, 0x61, 0x73,
	0x6f, 0x6e, 0x22, 0x18, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x57, 0x6f, 0x72, 0x6b, 0x6c, 0x6f, 0x61,
	0x64, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x8f, 0x01, 0x0a,
	0x17, 0x47, 0x65, 0x74, 0x57, 0x6f, 0x72, 0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x13, 0x0a, 0x05, 0x69, 0x73, 0x5f, 0x6f,
	0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x69, 0x73, 0x4f, 0x6b, 0x12, 0x25, 0x0a,
	0x0e, 0x66, 0x61, 0x69, 0x6c, 0x75, 0x72, 0x65, 0x5f, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x66, 0x61, 0x69, 0x6c, 0x75, 0x72, 0x65, 0x52, 0x65,
	0x61, 0x73, 0x6f, 0x6e, 0x12, 0x38, 0x0a, 0x0d, 0x77, 0x6f, 0x72, 0x6b, 0x6c, 0x6f, 0x61, 0x64,
	0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x0c, 0x77, 0x6f, 0x72, 0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x89,
	0x02, 0x0a, 0x0c, 0x57, 0x6f, 0x72, 0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x12,
	0x23, 0x0a, 0x0d, 0x77, 0x6f, 0x72, 0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x77, 0x6f, 0x72, 0x6b, 0x6c, 0x6f, 0x61, 0x64,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x33, 0x0a, 0x0e, 0x61, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x64,
	0x5f, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x0d, 0x61, 0x73, 0x73, 0x69,
	0x67, 0x6e, 0x65, 0x64, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x61, 0x62,
	0x6c, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74,
	0x61, 0x62, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x64, 0x75, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x73, 0x65, 0x63, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b,
	0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x63, 0x12, 0x20, 0x0a, 0x0b, 0x63,
	0x6f, 0x6e, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0b, 0x63, 0x6f, 0x6e, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x12, 0x1d, 0x0a,
	0x0a, 0x62, 0x61, 0x74, 0x63, 0x68, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x09, 0x62, 0x61, 0x74, 0x63, 0x68, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x1c, 0x0a, 0x09,
	0x69, 0x73, 0x52, 0x75, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x18, 0x07, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x09, 0x69, 0x73, 0x52, 0x75, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x22, 0x15, 0x0a, 0x13, 0x53, 0x74,
	0x6f, 0x70, 0x57, 0x6f, 0x72, 0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x22, 0x52, 0x0a, 0x14, 0x53, 0x74, 0x6f, 0x70, 0x57, 0x6f, 0x72, 0x6b, 0x6c, 0x6f, 0x61,
	0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x13, 0x0a, 0x05, 0x69, 0x73, 0x5f,
	0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x69, 0x73, 0x4f, 0x6b, 0x12, 0x25,
	0x0a, 0x0e, 0x66, 0x61, 0x69, 0x6c, 0x75, 0x72, 0x65, 0x5f, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x66, 0x61, 0x69, 0x6c, 0x75, 0x72, 0x65, 0x52,
	0x65, 0x61, 0x73, 0x6f, 0x6e, 0x32, 0xc0, 0x05, 0x0a, 0x06, 0x4d, 0x69, 0x6e, 0x69, 0x6f, 0x6e,
	0x12, 0x2f, 0x0a, 0x04, 0x50, 0x69, 0x6e, 0x67, 0x12, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x47, 0x0a, 0x0c, 0x4c, 0x6f, 0x61, 0x64, 0x44, 0x61, 0x74, 0x61, 0x53, 0x70, 0x65,
	0x63, 0x12, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4c, 0x6f, 0x61, 0x64, 0x44, 0x61,
	0x74, 0x61, 0x53, 0x70, 0x65, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4c, 0x6f, 0x61, 0x64, 0x44, 0x61, 0x74, 0x61, 0x53, 0x70,
	0x65, 0x63, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x50, 0x0a, 0x0f, 0x47, 0x65,
	0x74, 0x44, 0x61, 0x74, 0x61, 0x53, 0x70, 0x65, 0x63, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1d, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x61, 0x74, 0x61, 0x53, 0x70, 0x65,
	0x63, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x61, 0x74, 0x61, 0x53, 0x70, 0x65, 0x63,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x53, 0x0a, 0x10,
	0x4f, 0x70, 0x65, 0x6e, 0x44, 0x42, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x1e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4f, 0x70, 0x65, 0x6e, 0x44, 0x42, 0x43,
	0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4f, 0x70, 0x65, 0x6e, 0x44, 0x42, 0x43,
	0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x5c, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x44, 0x42, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x21, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x47, 0x65, 0x74, 0x44, 0x42, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x42, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x56, 0x0a, 0x11, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x44, 0x42, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x6c, 0x6f,
	0x73, 0x65, 0x44, 0x42, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x6c,
	0x6f, 0x73, 0x65, 0x44, 0x42, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x44, 0x0a, 0x0b, 0x52, 0x75, 0x6e, 0x57, 0x6f,
	0x72, 0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52,
	0x75, 0x6e, 0x57, 0x6f, 0x72, 0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x75, 0x6e, 0x57, 0x6f, 0x72,
	0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x50, 0x0a,
	0x0f, 0x47, 0x65, 0x74, 0x57, 0x6f, 0x72, 0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x49, 0x6e, 0x66, 0x6f,
	0x12, 0x1d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x57, 0x6f, 0x72, 0x6b,
	0x6c, 0x6f, 0x61, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x57, 0x6f, 0x72, 0x6b, 0x6c,
	0x6f, 0x61, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x47, 0x0a, 0x0c, 0x53, 0x74, 0x6f, 0x70, 0x57, 0x6f, 0x72, 0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x12,
	0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x74, 0x6f, 0x70, 0x57, 0x6f, 0x72, 0x6b,
	0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x74, 0x6f, 0x70, 0x57, 0x6f, 0x72, 0x6b, 0x6c, 0x6f, 0x61, 0x64,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_diligent_proto_rawDescOnce sync.Once
	file_diligent_proto_rawDescData = file_diligent_proto_rawDesc
)

func file_diligent_proto_rawDescGZIP() []byte {
	file_diligent_proto_rawDescOnce.Do(func() {
		file_diligent_proto_rawDescData = protoimpl.X.CompressGZIP(file_diligent_proto_rawDescData)
	})
	return file_diligent_proto_rawDescData
}

var file_diligent_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_diligent_proto_goTypes = []interface{}{
	(*PingRequest)(nil),                 // 0: proto.PingRequest
	(*PingResponse)(nil),                // 1: proto.PingResponse
	(*DataSpec)(nil),                    // 2: proto.DataSpec
	(*KeyGenSpec)(nil),                  // 3: proto.KeyGenSpec
	(*TrSpec)(nil),                      // 4: proto.TrSpec
	(*DataSpecInfo)(nil),                // 5: proto.DataSpecInfo
	(*LoadDataSpecRequest)(nil),         // 6: proto.LoadDataSpecRequest
	(*LoadDataSpecResponse)(nil),        // 7: proto.LoadDataSpecResponse
	(*GetDataSpecInfoRequest)(nil),      // 8: proto.GetDataSpecInfoRequest
	(*GetDataSpecInfoResponse)(nil),     // 9: proto.GetDataSpecInfoResponse
	(*OpenDBConnectionRequest)(nil),     // 10: proto.OpenDBConnectionRequest
	(*OpenDBConnectionResponse)(nil),    // 11: proto.OpenDBConnectionResponse
	(*GetDBConnectionInfoRequest)(nil),  // 12: proto.GetDBConnectionInfoRequest
	(*GetDBConnectionInfoResponse)(nil), // 13: proto.GetDBConnectionInfoResponse
	(*CloseDBConnectionRequest)(nil),    // 14: proto.CloseDBConnectionRequest
	(*CloseDBConnectionResponse)(nil),   // 15: proto.CloseDBConnectionResponse
	(*RunWorkloadRequest)(nil),          // 16: proto.RunWorkloadRequest
	(*Range)(nil),                       // 17: proto.Range
	(*RunWorkloadResponse)(nil),         // 18: proto.RunWorkloadResponse
	(*GetWorkloadInfoRequest)(nil),      // 19: proto.GetWorkloadInfoRequest
	(*GetWorkloadInfoResponse)(nil),     // 20: proto.GetWorkloadInfoResponse
	(*WorkloadInfo)(nil),                // 21: proto.WorkloadInfo
	(*StopWorkloadRequest)(nil),         // 22: proto.StopWorkloadRequest
	(*StopWorkloadResponse)(nil),        // 23: proto.StopWorkloadResponse
}
var file_diligent_proto_depIdxs = []int32{
	3,  // 0: proto.DataSpec.key_gen_spec:type_name -> proto.KeyGenSpec
	4,  // 1: proto.DataSpec.uniq_tr_spec:type_name -> proto.TrSpec
	4,  // 2: proto.DataSpec.small_grp_tr_spec:type_name -> proto.TrSpec
	4,  // 3: proto.DataSpec.large_grp_tr_spec:type_name -> proto.TrSpec
	2,  // 4: proto.LoadDataSpecRequest.data_spec:type_name -> proto.DataSpec
	5,  // 5: proto.LoadDataSpecResponse.data_spec_info:type_name -> proto.DataSpecInfo
	5,  // 6: proto.GetDataSpecInfoResponse.data_spec_info:type_name -> proto.DataSpecInfo
	17, // 7: proto.RunWorkloadRequest.assigned_range:type_name -> proto.Range
	21, // 8: proto.GetWorkloadInfoResponse.workload_info:type_name -> proto.WorkloadInfo
	17, // 9: proto.WorkloadInfo.assigned_range:type_name -> proto.Range
	0,  // 10: proto.Minion.Ping:input_type -> proto.PingRequest
	6,  // 11: proto.Minion.LoadDataSpec:input_type -> proto.LoadDataSpecRequest
	8,  // 12: proto.Minion.GetDataSpecInfo:input_type -> proto.GetDataSpecInfoRequest
	10, // 13: proto.Minion.OpenDBConnection:input_type -> proto.OpenDBConnectionRequest
	12, // 14: proto.Minion.GetDBConnectionInfo:input_type -> proto.GetDBConnectionInfoRequest
	14, // 15: proto.Minion.CloseDBConnection:input_type -> proto.CloseDBConnectionRequest
	16, // 16: proto.Minion.RunWorkload:input_type -> proto.RunWorkloadRequest
	19, // 17: proto.Minion.GetWorkloadInfo:input_type -> proto.GetWorkloadInfoRequest
	22, // 18: proto.Minion.StopWorkload:input_type -> proto.StopWorkloadRequest
	1,  // 19: proto.Minion.Ping:output_type -> proto.PingResponse
	7,  // 20: proto.Minion.LoadDataSpec:output_type -> proto.LoadDataSpecResponse
	9,  // 21: proto.Minion.GetDataSpecInfo:output_type -> proto.GetDataSpecInfoResponse
	11, // 22: proto.Minion.OpenDBConnection:output_type -> proto.OpenDBConnectionResponse
	13, // 23: proto.Minion.GetDBConnectionInfo:output_type -> proto.GetDBConnectionInfoResponse
	15, // 24: proto.Minion.CloseDBConnection:output_type -> proto.CloseDBConnectionResponse
	18, // 25: proto.Minion.RunWorkload:output_type -> proto.RunWorkloadResponse
	20, // 26: proto.Minion.GetWorkloadInfo:output_type -> proto.GetWorkloadInfoResponse
	23, // 27: proto.Minion.StopWorkload:output_type -> proto.StopWorkloadResponse
	19, // [19:28] is the sub-list for method output_type
	10, // [10:19] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_diligent_proto_init() }
func file_diligent_proto_init() {
	if File_diligent_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_diligent_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_diligent_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_diligent_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataSpec); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_diligent_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KeyGenSpec); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_diligent_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TrSpec); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_diligent_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataSpecInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_diligent_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoadDataSpecRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_diligent_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoadDataSpecResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_diligent_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDataSpecInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_diligent_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDataSpecInfoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_diligent_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OpenDBConnectionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_diligent_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OpenDBConnectionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_diligent_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDBConnectionInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_diligent_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDBConnectionInfoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_diligent_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CloseDBConnectionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_diligent_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CloseDBConnectionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_diligent_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RunWorkloadRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_diligent_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Range); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_diligent_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RunWorkloadResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_diligent_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetWorkloadInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_diligent_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetWorkloadInfoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_diligent_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WorkloadInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_diligent_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StopWorkloadRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_diligent_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StopWorkloadResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_diligent_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_diligent_proto_goTypes,
		DependencyIndexes: file_diligent_proto_depIdxs,
		MessageInfos:      file_diligent_proto_msgTypes,
	}.Build()
	File_diligent_proto = out.File
	file_diligent_proto_rawDesc = nil
	file_diligent_proto_goTypes = nil
	file_diligent_proto_depIdxs = nil
}
