// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: diligent_boss.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExperimentState int32

const (
	ExperimentState_UNDEFINED_EXPERIMENT_STATE ExperimentState = 0
	ExperimentState_NEW_EXPERIMENT             ExperimentState = 1
	ExperimentState_STARTED                    ExperimentState = 2
	ExperimentState_STOPPED                    ExperimentState = 3
)

// Enum value maps for ExperimentState.
var (
	ExperimentState_name = map[int32]string{
		0: "UNDEFINED_EXPERIMENT_STATE",
		1: "NEW_EXPERIMENT",
		2: "STARTED",
		3: "STOPPED",
	}
	ExperimentState_value = map[string]int32{
		"UNDEFINED_EXPERIMENT_STATE": 0,
		"NEW_EXPERIMENT":             1,
		"STARTED":                    2,
		"STOPPED":                    3,
	}
)

func (x ExperimentState) Enum() *ExperimentState {
	p := new(ExperimentState)
	*p = x
	return p
}

func (x ExperimentState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExperimentState) Descriptor() protoreflect.EnumDescriptor {
	return file_diligent_boss_proto_enumTypes[0].Descriptor()
}

func (ExperimentState) Type() protoreflect.EnumType {
	return &file_diligent_boss_proto_enumTypes[0]
}

func (x ExperimentState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExperimentState.Descriptor instead.
func (ExperimentState) EnumDescriptor() ([]byte, []int) {
	return file_diligent_boss_proto_rawDescGZIP(), []int{0}
}

type BossPingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *BossPingRequest) Reset() {
	*x = BossPingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_diligent_boss_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BossPingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BossPingRequest) ProtoMessage() {}

func (x *BossPingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_diligent_boss_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BossPingRequest.ProtoReflect.Descriptor instead.
func (*BossPingRequest) Descriptor() ([]byte, []int) {
	return file_diligent_boss_proto_rawDescGZIP(), []int{0}
}

type BossPingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BuildInfo   *BuildInfo   `protobuf:"bytes,1,opt,name=build_info,json=buildInfo,proto3" json:"build_info,omitempty"`
	ProcessInfo *ProcessInfo `protobuf:"bytes,2,opt,name=process_info,json=processInfo,proto3" json:"process_info,omitempty"`
}

func (x *BossPingResponse) Reset() {
	*x = BossPingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_diligent_boss_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BossPingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BossPingResponse) ProtoMessage() {}

func (x *BossPingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_diligent_boss_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BossPingResponse.ProtoReflect.Descriptor instead.
func (*BossPingResponse) Descriptor() ([]byte, []int) {
	return file_diligent_boss_proto_rawDescGZIP(), []int{1}
}

func (x *BossPingResponse) GetBuildInfo() *BuildInfo {
	if x != nil {
		return x.BuildInfo
	}
	return nil
}

func (x *BossPingResponse) GetProcessInfo() *ProcessInfo {
	if x != nil {
		return x.ProcessInfo
	}
	return nil
}

type BossRegisterMinionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Addr string `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
}

func (x *BossRegisterMinionRequest) Reset() {
	*x = BossRegisterMinionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_diligent_boss_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BossRegisterMinionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BossRegisterMinionRequest) ProtoMessage() {}

func (x *BossRegisterMinionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_diligent_boss_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BossRegisterMinionRequest.ProtoReflect.Descriptor instead.
func (*BossRegisterMinionRequest) Descriptor() ([]byte, []int) {
	return file_diligent_boss_proto_rawDescGZIP(), []int{2}
}

func (x *BossRegisterMinionRequest) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

type BossRegisterMinionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status *GeneralStatus `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *BossRegisterMinionResponse) Reset() {
	*x = BossRegisterMinionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_diligent_boss_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BossRegisterMinionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BossRegisterMinionResponse) ProtoMessage() {}

func (x *BossRegisterMinionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_diligent_boss_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BossRegisterMinionResponse.ProtoReflect.Descriptor instead.
func (*BossRegisterMinionResponse) Descriptor() ([]byte, []int) {
	return file_diligent_boss_proto_rawDescGZIP(), []int{3}
}

func (x *BossRegisterMinionResponse) GetStatus() *GeneralStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

type BossUnregisterMinionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Addr string `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
}

func (x *BossUnregisterMinionRequest) Reset() {
	*x = BossUnregisterMinionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_diligent_boss_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BossUnregisterMinionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BossUnregisterMinionRequest) ProtoMessage() {}

func (x *BossUnregisterMinionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_diligent_boss_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BossUnregisterMinionRequest.ProtoReflect.Descriptor instead.
func (*BossUnregisterMinionRequest) Descriptor() ([]byte, []int) {
	return file_diligent_boss_proto_rawDescGZIP(), []int{4}
}

func (x *BossUnregisterMinionRequest) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

type BossUnregisterMinionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status *GeneralStatus `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *BossUnregisterMinionResponse) Reset() {
	*x = BossUnregisterMinionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_diligent_boss_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BossUnregisterMinionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BossUnregisterMinionResponse) ProtoMessage() {}

func (x *BossUnregisterMinionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_diligent_boss_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BossUnregisterMinionResponse.ProtoReflect.Descriptor instead.
func (*BossUnregisterMinionResponse) Descriptor() ([]byte, []int) {
	return file_diligent_boss_proto_rawDescGZIP(), []int{5}
}

func (x *BossUnregisterMinionResponse) GetStatus() *GeneralStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

type MinionInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Addr         string         `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	Reachability *GeneralStatus `protobuf:"bytes,2,opt,name=reachability,proto3" json:"reachability,omitempty"`
	BuildInfo    *BuildInfo     `protobuf:"bytes,3,opt,name=build_info,json=buildInfo,proto3" json:"build_info,omitempty"`
	ProcessInfo  *ProcessInfo   `protobuf:"bytes,4,opt,name=process_info,json=processInfo,proto3" json:"process_info,omitempty"`
	JobInfo      *MinionJobInfo `protobuf:"bytes,5,opt,name=job_info,json=jobInfo,proto3" json:"job_info,omitempty"`
}

func (x *MinionInfo) Reset() {
	*x = MinionInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_diligent_boss_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MinionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MinionInfo) ProtoMessage() {}

func (x *MinionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_diligent_boss_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MinionInfo.ProtoReflect.Descriptor instead.
func (*MinionInfo) Descriptor() ([]byte, []int) {
	return file_diligent_boss_proto_rawDescGZIP(), []int{6}
}

func (x *MinionInfo) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *MinionInfo) GetReachability() *GeneralStatus {
	if x != nil {
		return x.Reachability
	}
	return nil
}

func (x *MinionInfo) GetBuildInfo() *BuildInfo {
	if x != nil {
		return x.BuildInfo
	}
	return nil
}

func (x *MinionInfo) GetProcessInfo() *ProcessInfo {
	if x != nil {
		return x.ProcessInfo
	}
	return nil
}

func (x *MinionInfo) GetJobInfo() *MinionJobInfo {
	if x != nil {
		return x.JobInfo
	}
	return nil
}

type MinionStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Addr   string         `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	Status *GeneralStatus `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *MinionStatus) Reset() {
	*x = MinionStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_diligent_boss_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MinionStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MinionStatus) ProtoMessage() {}

func (x *MinionStatus) ProtoReflect() protoreflect.Message {
	mi := &file_diligent_boss_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MinionStatus.ProtoReflect.Descriptor instead.
func (*MinionStatus) Descriptor() ([]byte, []int) {
	return file_diligent_boss_proto_rawDescGZIP(), []int{7}
}

func (x *MinionStatus) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *MinionStatus) GetStatus() *GeneralStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

type BossGetMinionInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *BossGetMinionInfoRequest) Reset() {
	*x = BossGetMinionInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_diligent_boss_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BossGetMinionInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BossGetMinionInfoRequest) ProtoMessage() {}

func (x *BossGetMinionInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_diligent_boss_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BossGetMinionInfoRequest.ProtoReflect.Descriptor instead.
func (*BossGetMinionInfoRequest) Descriptor() ([]byte, []int) {
	return file_diligent_boss_proto_rawDescGZIP(), []int{8}
}

type BossGetMinionInfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MinionInfos []*MinionInfo `protobuf:"bytes,1,rep,name=minion_infos,json=minionInfos,proto3" json:"minion_infos,omitempty"`
}

func (x *BossGetMinionInfoResponse) Reset() {
	*x = BossGetMinionInfoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_diligent_boss_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BossGetMinionInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BossGetMinionInfoResponse) ProtoMessage() {}

func (x *BossGetMinionInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_diligent_boss_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BossGetMinionInfoResponse.ProtoReflect.Descriptor instead.
func (*BossGetMinionInfoResponse) Descriptor() ([]byte, []int) {
	return file_diligent_boss_proto_rawDescGZIP(), []int{9}
}

func (x *BossGetMinionInfoResponse) GetMinionInfos() []*MinionInfo {
	if x != nil {
		return x.MinionInfos
	}
	return nil
}

type BossPrepareJobRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JobSpec *JobSpec `protobuf:"bytes,1,opt,name=job_spec,json=jobSpec,proto3" json:"job_spec,omitempty"`
}

func (x *BossPrepareJobRequest) Reset() {
	*x = BossPrepareJobRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_diligent_boss_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BossPrepareJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BossPrepareJobRequest) ProtoMessage() {}

func (x *BossPrepareJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_diligent_boss_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BossPrepareJobRequest.ProtoReflect.Descriptor instead.
func (*BossPrepareJobRequest) Descriptor() ([]byte, []int) {
	return file_diligent_boss_proto_rawDescGZIP(), []int{10}
}

func (x *BossPrepareJobRequest) GetJobSpec() *JobSpec {
	if x != nil {
		return x.JobSpec
	}
	return nil
}

type BossPrepareJobResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status         *GeneralStatus  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	MinionStatuses []*MinionStatus `protobuf:"bytes,2,rep,name=minion_statuses,json=minionStatuses,proto3" json:"minion_statuses,omitempty"`
}

func (x *BossPrepareJobResponse) Reset() {
	*x = BossPrepareJobResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_diligent_boss_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BossPrepareJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BossPrepareJobResponse) ProtoMessage() {}

func (x *BossPrepareJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_diligent_boss_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BossPrepareJobResponse.ProtoReflect.Descriptor instead.
func (*BossPrepareJobResponse) Descriptor() ([]byte, []int) {
	return file_diligent_boss_proto_rawDescGZIP(), []int{11}
}

func (x *BossPrepareJobResponse) GetStatus() *GeneralStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *BossPrepareJobResponse) GetMinionStatuses() []*MinionStatus {
	if x != nil {
		return x.MinionStatuses
	}
	return nil
}

type BossRunJobRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *BossRunJobRequest) Reset() {
	*x = BossRunJobRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_diligent_boss_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BossRunJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BossRunJobRequest) ProtoMessage() {}

func (x *BossRunJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_diligent_boss_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BossRunJobRequest.ProtoReflect.Descriptor instead.
func (*BossRunJobRequest) Descriptor() ([]byte, []int) {
	return file_diligent_boss_proto_rawDescGZIP(), []int{12}
}

type BossRunJobResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status         *GeneralStatus  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	MinionStatuses []*MinionStatus `protobuf:"bytes,2,rep,name=minion_statuses,json=minionStatuses,proto3" json:"minion_statuses,omitempty"`
}

func (x *BossRunJobResponse) Reset() {
	*x = BossRunJobResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_diligent_boss_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BossRunJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BossRunJobResponse) ProtoMessage() {}

func (x *BossRunJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_diligent_boss_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BossRunJobResponse.ProtoReflect.Descriptor instead.
func (*BossRunJobResponse) Descriptor() ([]byte, []int) {
	return file_diligent_boss_proto_rawDescGZIP(), []int{13}
}

func (x *BossRunJobResponse) GetStatus() *GeneralStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *BossRunJobResponse) GetMinionStatuses() []*MinionStatus {
	if x != nil {
		return x.MinionStatuses
	}
	return nil
}

type BossAbortJobRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *BossAbortJobRequest) Reset() {
	*x = BossAbortJobRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_diligent_boss_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BossAbortJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BossAbortJobRequest) ProtoMessage() {}

func (x *BossAbortJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_diligent_boss_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BossAbortJobRequest.ProtoReflect.Descriptor instead.
func (*BossAbortJobRequest) Descriptor() ([]byte, []int) {
	return file_diligent_boss_proto_rawDescGZIP(), []int{14}
}

type BossAbortJobResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status         *GeneralStatus  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	MinionStatuses []*MinionStatus `protobuf:"bytes,2,rep,name=minion_statuses,json=minionStatuses,proto3" json:"minion_statuses,omitempty"`
}

func (x *BossAbortJobResponse) Reset() {
	*x = BossAbortJobResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_diligent_boss_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BossAbortJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BossAbortJobResponse) ProtoMessage() {}

func (x *BossAbortJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_diligent_boss_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BossAbortJobResponse.ProtoReflect.Descriptor instead.
func (*BossAbortJobResponse) Descriptor() ([]byte, []int) {
	return file_diligent_boss_proto_rawDescGZIP(), []int{15}
}

func (x *BossAbortJobResponse) GetStatus() *GeneralStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *BossAbortJobResponse) GetMinionStatuses() []*MinionStatus {
	if x != nil {
		return x.MinionStatuses
	}
	return nil
}

type BossJobInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JobSpec     *JobSpec `protobuf:"bytes,1,opt,name=job_spec,json=jobSpec,proto3" json:"job_spec,omitempty"`
	JobState    JobState `protobuf:"varint,2,opt,name=job_state,json=jobState,proto3,enum=proto.JobState" json:"job_state,omitempty"`
	PrepareTime int64    `protobuf:"varint,3,opt,name=prepare_time,json=prepareTime,proto3" json:"prepare_time,omitempty"`
	RunTime     int64    `protobuf:"varint,4,opt,name=run_time,json=runTime,proto3" json:"run_time,omitempty"`
	EndTime     int64    `protobuf:"varint,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	MinionAddrs []string `protobuf:"bytes,6,rep,name=minion_addrs,json=minionAddrs,proto3" json:"minion_addrs,omitempty"`
}

func (x *BossJobInfo) Reset() {
	*x = BossJobInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_diligent_boss_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BossJobInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BossJobInfo) ProtoMessage() {}

func (x *BossJobInfo) ProtoReflect() protoreflect.Message {
	mi := &file_diligent_boss_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BossJobInfo.ProtoReflect.Descriptor instead.
func (*BossJobInfo) Descriptor() ([]byte, []int) {
	return file_diligent_boss_proto_rawDescGZIP(), []int{16}
}

func (x *BossJobInfo) GetJobSpec() *JobSpec {
	if x != nil {
		return x.JobSpec
	}
	return nil
}

func (x *BossJobInfo) GetJobState() JobState {
	if x != nil {
		return x.JobState
	}
	return JobState_UNDEFINED_JOB_STATE
}

func (x *BossJobInfo) GetPrepareTime() int64 {
	if x != nil {
		return x.PrepareTime
	}
	return 0
}

func (x *BossJobInfo) GetRunTime() int64 {
	if x != nil {
		return x.RunTime
	}
	return 0
}

func (x *BossJobInfo) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *BossJobInfo) GetMinionAddrs() []string {
	if x != nil {
		return x.MinionAddrs
	}
	return nil
}

type BossGetJobInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *BossGetJobInfoRequest) Reset() {
	*x = BossGetJobInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_diligent_boss_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BossGetJobInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BossGetJobInfoRequest) ProtoMessage() {}

func (x *BossGetJobInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_diligent_boss_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BossGetJobInfoRequest.ProtoReflect.Descriptor instead.
func (*BossGetJobInfoRequest) Descriptor() ([]byte, []int) {
	return file_diligent_boss_proto_rawDescGZIP(), []int{17}
}

type BossGetJobInfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  *GeneralStatus `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	JobInfo *BossJobInfo   `protobuf:"bytes,2,opt,name=job_info,json=jobInfo,proto3" json:"job_info,omitempty"`
}

func (x *BossGetJobInfoResponse) Reset() {
	*x = BossGetJobInfoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_diligent_boss_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BossGetJobInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BossGetJobInfoResponse) ProtoMessage() {}

func (x *BossGetJobInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_diligent_boss_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BossGetJobInfoResponse.ProtoReflect.Descriptor instead.
func (*BossGetJobInfoResponse) Descriptor() ([]byte, []int) {
	return file_diligent_boss_proto_rawDescGZIP(), []int{18}
}

func (x *BossGetJobInfoResponse) GetStatus() *GeneralStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *BossGetJobInfoResponse) GetJobInfo() *BossJobInfo {
	if x != nil {
		return x.JobInfo
	}
	return nil
}

type ExperimentInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name      string          `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	State     ExperimentState `protobuf:"varint,2,opt,name=state,proto3,enum=proto.ExperimentState" json:"state,omitempty"`
	StartTime int64           `protobuf:"varint,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	StopTime  int64           `protobuf:"varint,4,opt,name=stop_time,json=stopTime,proto3" json:"stop_time,omitempty"`
}

func (x *ExperimentInfo) Reset() {
	*x = ExperimentInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_diligent_boss_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExperimentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExperimentInfo) ProtoMessage() {}

func (x *ExperimentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_diligent_boss_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExperimentInfo.ProtoReflect.Descriptor instead.
func (*ExperimentInfo) Descriptor() ([]byte, []int) {
	return file_diligent_boss_proto_rawDescGZIP(), []int{19}
}

func (x *ExperimentInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ExperimentInfo) GetState() ExperimentState {
	if x != nil {
		return x.State
	}
	return ExperimentState_UNDEFINED_EXPERIMENT_STATE
}

func (x *ExperimentInfo) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *ExperimentInfo) GetStopTime() int64 {
	if x != nil {
		return x.StopTime
	}
	return 0
}

type BossStartExperimentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ExperimentName string `protobuf:"bytes,1,opt,name=experiment_name,json=experimentName,proto3" json:"experiment_name,omitempty"`
}

func (x *BossStartExperimentRequest) Reset() {
	*x = BossStartExperimentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_diligent_boss_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BossStartExperimentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BossStartExperimentRequest) ProtoMessage() {}

func (x *BossStartExperimentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_diligent_boss_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BossStartExperimentRequest.ProtoReflect.Descriptor instead.
func (*BossStartExperimentRequest) Descriptor() ([]byte, []int) {
	return file_diligent_boss_proto_rawDescGZIP(), []int{20}
}

func (x *BossStartExperimentRequest) GetExperimentName() string {
	if x != nil {
		return x.ExperimentName
	}
	return ""
}

type BossStartExperimentResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status *GeneralStatus `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *BossStartExperimentResponse) Reset() {
	*x = BossStartExperimentResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_diligent_boss_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BossStartExperimentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BossStartExperimentResponse) ProtoMessage() {}

func (x *BossStartExperimentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_diligent_boss_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BossStartExperimentResponse.ProtoReflect.Descriptor instead.
func (*BossStartExperimentResponse) Descriptor() ([]byte, []int) {
	return file_diligent_boss_proto_rawDescGZIP(), []int{21}
}

func (x *BossStartExperimentResponse) GetStatus() *GeneralStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

type BossStopExperimentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *BossStopExperimentRequest) Reset() {
	*x = BossStopExperimentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_diligent_boss_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BossStopExperimentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BossStopExperimentRequest) ProtoMessage() {}

func (x *BossStopExperimentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_diligent_boss_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BossStopExperimentRequest.ProtoReflect.Descriptor instead.
func (*BossStopExperimentRequest) Descriptor() ([]byte, []int) {
	return file_diligent_boss_proto_rawDescGZIP(), []int{22}
}

type BossStopExperimentResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status *GeneralStatus `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *BossStopExperimentResponse) Reset() {
	*x = BossStopExperimentResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_diligent_boss_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BossStopExperimentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BossStopExperimentResponse) ProtoMessage() {}

func (x *BossStopExperimentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_diligent_boss_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BossStopExperimentResponse.ProtoReflect.Descriptor instead.
func (*BossStopExperimentResponse) Descriptor() ([]byte, []int) {
	return file_diligent_boss_proto_rawDescGZIP(), []int{23}
}

func (x *BossStopExperimentResponse) GetStatus() *GeneralStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

type BossGetExperimentInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *BossGetExperimentInfoRequest) Reset() {
	*x = BossGetExperimentInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_diligent_boss_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BossGetExperimentInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BossGetExperimentInfoRequest) ProtoMessage() {}

func (x *BossGetExperimentInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_diligent_boss_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BossGetExperimentInfoRequest.ProtoReflect.Descriptor instead.
func (*BossGetExperimentInfoRequest) Descriptor() ([]byte, []int) {
	return file_diligent_boss_proto_rawDescGZIP(), []int{24}
}

type BossGetExperimentInfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status         *GeneralStatus  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	ExperimentInfo *ExperimentInfo `protobuf:"bytes,2,opt,name=experiment_info,json=experimentInfo,proto3" json:"experiment_info,omitempty"`
}

func (x *BossGetExperimentInfoResponse) Reset() {
	*x = BossGetExperimentInfoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_diligent_boss_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BossGetExperimentInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BossGetExperimentInfoResponse) ProtoMessage() {}

func (x *BossGetExperimentInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_diligent_boss_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BossGetExperimentInfoResponse.ProtoReflect.Descriptor instead.
func (*BossGetExperimentInfoResponse) Descriptor() ([]byte, []int) {
	return file_diligent_boss_proto_rawDescGZIP(), []int{25}
}

func (x *BossGetExperimentInfoResponse) GetStatus() *GeneralStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *BossGetExperimentInfoResponse) GetExperimentInfo() *ExperimentInfo {
	if x != nil {
		return x.ExperimentInfo
	}
	return nil
}

var File_diligent_boss_proto protoreflect.FileDescriptor

var file_diligent_boss_proto_rawDesc = []byte{
	0x0a, 0x13, 0x64, 0x69, 0x6c, 0x69, 0x67, 0x65, 0x6e, 0x74, 0x5f, 0x62, 0x6f, 0x73, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x15, 0x64, 0x69,
	0x6c, 0x69, 0x67, 0x65, 0x6e, 0x74, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x11, 0x0a, 0x0f, 0x42, 0x6f, 0x73, 0x73, 0x50, 0x69, 0x6e, 0x67, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x7a, 0x0a, 0x10, 0x42, 0x6f, 0x73, 0x73, 0x50, 0x69,
	0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2f, 0x0a, 0x0a, 0x62, 0x75,
	0x69, 0x6c, 0x64, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x09, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x35, 0x0a, 0x0c, 0x70,
	0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73,
	0x73, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0b, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x49, 0x6e,
	0x66, 0x6f, 0x22, 0x2f, 0x0a, 0x19, 0x42, 0x6f, 0x73, 0x73, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74,
	0x65, 0x72, 0x4d, 0x69, 0x6e, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x61, 0x64, 0x64, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x61,
	0x64, 0x64, 0x72, 0x22, 0x4a, 0x0a, 0x1a, 0x42, 0x6f, 0x73, 0x73, 0x52, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x65, 0x72, 0x4d, 0x69, 0x6e, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x2c, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61,
	0x6c, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22,
	0x31, 0x0a, 0x1b, 0x42, 0x6f, 0x73, 0x73, 0x55, 0x6e, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65,
	0x72, 0x4d, 0x69, 0x6e, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x61, 0x64, 0x64, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x61, 0x64,
	0x64, 0x72, 0x22, 0x4c, 0x0a, 0x1c, 0x42, 0x6f, 0x73, 0x73, 0x55, 0x6e, 0x72, 0x65, 0x67, 0x69,
	0x73, 0x74, 0x65, 0x72, 0x4d, 0x69, 0x6e, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x2c, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72,
	0x61, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x22, 0xf3, 0x01, 0x0a, 0x0a, 0x4d, 0x69, 0x6e, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x12,
	0x12, 0x0a, 0x04, 0x61, 0x64, 0x64, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x61,
	0x64, 0x64, 0x72, 0x12, 0x38, 0x0a, 0x0c, 0x72, 0x65, 0x61, 0x63, 0x68, 0x61, 0x62, 0x69, 0x6c,
	0x69, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52,
	0x0c, 0x72, 0x65, 0x61, 0x63, 0x68, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x12, 0x2f, 0x0a,
	0x0a, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x09, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x35,
	0x0a, 0x0c, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x72, 0x6f,
	0x63, 0x65, 0x73, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0b, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73,
	0x73, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x2f, 0x0a, 0x08, 0x6a, 0x6f, 0x62, 0x5f, 0x69, 0x6e, 0x66,
	0x6f, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x4d, 0x69, 0x6e, 0x69, 0x6f, 0x6e, 0x4a, 0x6f, 0x62, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x07, 0x6a,
	0x6f, 0x62, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x50, 0x0a, 0x0c, 0x4d, 0x69, 0x6e, 0x69, 0x6f, 0x6e,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x64, 0x64, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x61, 0x64, 0x64, 0x72, 0x12, 0x2c, 0x0a, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x1a, 0x0a, 0x18, 0x42, 0x6f, 0x73, 0x73,
	0x47, 0x65, 0x74, 0x4d, 0x69, 0x6e, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x22, 0x51, 0x0a, 0x19, 0x42, 0x6f, 0x73, 0x73, 0x47, 0x65, 0x74, 0x4d,
	0x69, 0x6e, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x34, 0x0a, 0x0c, 0x6d, 0x69, 0x6e, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x6e, 0x66, 0x6f,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x4d, 0x69, 0x6e, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0b, 0x6d, 0x69, 0x6e, 0x69,
	0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x73, 0x22, 0x42, 0x0a, 0x15, 0x42, 0x6f, 0x73, 0x73, 0x50,
	0x72, 0x65, 0x70, 0x61, 0x72, 0x65, 0x4a, 0x6f, 0x62, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x29, 0x0a, 0x08, 0x6a, 0x6f, 0x62, 0x5f, 0x73, 0x70, 0x65, 0x63, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4a, 0x6f, 0x62, 0x53, 0x70,
	0x65, 0x63, 0x52, 0x07, 0x6a, 0x6f, 0x62, 0x53, 0x70, 0x65, 0x63, 0x22, 0x84, 0x01, 0x0a, 0x16,
	0x42, 0x6f, 0x73, 0x73, 0x50, 0x72, 0x65, 0x70, 0x61, 0x72, 0x65, 0x4a, 0x6f, 0x62, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2c, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47,
	0x65, 0x6e, 0x65, 0x72, 0x61, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x3c, 0x0a, 0x0f, 0x6d, 0x69, 0x6e, 0x69, 0x6f, 0x6e, 0x5f, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4d, 0x69, 0x6e, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x52, 0x0e, 0x6d, 0x69, 0x6e, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x65, 0x73, 0x22, 0x13, 0x0a, 0x11, 0x42, 0x6f, 0x73, 0x73, 0x52, 0x75, 0x6e, 0x4a, 0x6f, 0x62,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x80, 0x01, 0x0a, 0x12, 0x42, 0x6f, 0x73, 0x73,
	0x52, 0x75, 0x6e, 0x4a, 0x6f, 0x62, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2c,
	0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x6c, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x3c, 0x0a, 0x0f,
	0x6d, 0x69, 0x6e, 0x69, 0x6f, 0x6e, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x65, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4d, 0x69,
	0x6e, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x0e, 0x6d, 0x69, 0x6e, 0x69,
	0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x65, 0x73, 0x22, 0x15, 0x0a, 0x13, 0x42, 0x6f,
	0x73, 0x73, 0x41, 0x62, 0x6f, 0x72, 0x74, 0x4a, 0x6f, 0x62, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x22, 0x82, 0x01, 0x0a, 0x14, 0x42, 0x6f, 0x73, 0x73, 0x41, 0x62, 0x6f, 0x72, 0x74, 0x4a,
	0x6f, 0x62, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2c, 0x0a, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x3c, 0x0a, 0x0f, 0x6d, 0x69, 0x6e, 0x69,
	0x6f, 0x6e, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4d, 0x69, 0x6e, 0x69, 0x6f, 0x6e,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x0e, 0x6d, 0x69, 0x6e, 0x69, 0x6f, 0x6e, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x65, 0x73, 0x22, 0xe2, 0x01, 0x0a, 0x0b, 0x42, 0x6f, 0x73, 0x73, 0x4a,
	0x6f, 0x62, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x29, 0x0a, 0x08, 0x6a, 0x6f, 0x62, 0x5f, 0x73, 0x70,
	0x65, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x4a, 0x6f, 0x62, 0x53, 0x70, 0x65, 0x63, 0x52, 0x07, 0x6a, 0x6f, 0x62, 0x53, 0x70, 0x65,
	0x63, 0x12, 0x2c, 0x0a, 0x09, 0x6a, 0x6f, 0x62, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4a, 0x6f, 0x62,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x08, 0x6a, 0x6f, 0x62, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12,
	0x21, 0x0a, 0x0c, 0x70, 0x72, 0x65, 0x70, 0x61, 0x72, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x70, 0x72, 0x65, 0x70, 0x61, 0x72, 0x65, 0x54, 0x69,
	0x6d, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x72, 0x75, 0x6e, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x72, 0x75, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x19, 0x0a,
	0x08, 0x65, 0x6e, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x07, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x6d, 0x69, 0x6e, 0x69,
	0x6f, 0x6e, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0b,
	0x6d, 0x69, 0x6e, 0x69, 0x6f, 0x6e, 0x41, 0x64, 0x64, 0x72, 0x73, 0x22, 0x17, 0x0a, 0x15, 0x42,
	0x6f, 0x73, 0x73, 0x47, 0x65, 0x74, 0x4a, 0x6f, 0x62, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x22, 0x75, 0x0a, 0x16, 0x42, 0x6f, 0x73, 0x73, 0x47, 0x65, 0x74, 0x4a,
	0x6f, 0x62, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2c,
	0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x6c, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x2d, 0x0a, 0x08,
	0x6a, 0x6f, 0x62, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x6f, 0x73, 0x73, 0x4a, 0x6f, 0x62, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x07, 0x6a, 0x6f, 0x62, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x8e, 0x01, 0x0a, 0x0e,
	0x45, 0x78, 0x70, 0x65, 0x72, 0x69, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x2c, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x78, 0x70, 0x65, 0x72, 0x69,
	0x6d, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65,
	0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12,
	0x1b, 0x0a, 0x09, 0x73, 0x74, 0x6f, 0x70, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x08, 0x73, 0x74, 0x6f, 0x70, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x45, 0x0a, 0x1a,
	0x42, 0x6f, 0x73, 0x73, 0x53, 0x74, 0x61, 0x72, 0x74, 0x45, 0x78, 0x70, 0x65, 0x72, 0x69, 0x6d,
	0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x27, 0x0a, 0x0f, 0x65, 0x78,
	0x70, 0x65, 0x72, 0x69, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0e, 0x65, 0x78, 0x70, 0x65, 0x72, 0x69, 0x6d, 0x65, 0x6e, 0x74, 0x4e,
	0x61, 0x6d, 0x65, 0x22, 0x4b, 0x0a, 0x1b, 0x42, 0x6f, 0x73, 0x73, 0x53, 0x74, 0x61, 0x72, 0x74,
	0x45, 0x78, 0x70, 0x65, 0x72, 0x69, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x2c, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72,
	0x61, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x22, 0x1b, 0x0a, 0x19, 0x42, 0x6f, 0x73, 0x73, 0x53, 0x74, 0x6f, 0x70, 0x45, 0x78, 0x70, 0x65,
	0x72, 0x69, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x4a, 0x0a,
	0x1a, 0x42, 0x6f, 0x73, 0x73, 0x53, 0x74, 0x6f, 0x70, 0x45, 0x78, 0x70, 0x65, 0x72, 0x69, 0x6d,
	0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2c, 0x0a, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x1e, 0x0a, 0x1c, 0x42, 0x6f, 0x73,
	0x73, 0x47, 0x65, 0x74, 0x45, 0x78, 0x70, 0x65, 0x72, 0x69, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x8d, 0x01, 0x0a, 0x1d, 0x42, 0x6f,
	0x73, 0x73, 0x47, 0x65, 0x74, 0x45, 0x78, 0x70, 0x65, 0x72, 0x69, 0x6d, 0x65, 0x6e, 0x74, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2c, 0x0a, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x3e, 0x0a, 0x0f, 0x65, 0x78, 0x70,
	0x65, 0x72, 0x69, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x78, 0x70, 0x65, 0x72,
	0x69, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0e, 0x65, 0x78, 0x70, 0x65, 0x72,
	0x69, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x2a, 0x5f, 0x0a, 0x0f, 0x45, 0x78, 0x70,
	0x65, 0x72, 0x69, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x1e, 0x0a, 0x1a,
	0x55, 0x4e, 0x44, 0x45, 0x46, 0x49, 0x4e, 0x45, 0x44, 0x5f, 0x45, 0x58, 0x50, 0x45, 0x52, 0x49,
	0x4d, 0x45, 0x4e, 0x54, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x10, 0x00, 0x12, 0x12, 0x0a, 0x0e,
	0x4e, 0x45, 0x57, 0x5f, 0x45, 0x58, 0x50, 0x45, 0x52, 0x49, 0x4d, 0x45, 0x4e, 0x54, 0x10, 0x01,
	0x12, 0x0b, 0x0a, 0x07, 0x53, 0x54, 0x41, 0x52, 0x54, 0x45, 0x44, 0x10, 0x02, 0x12, 0x0b, 0x0a,
	0x07, 0x53, 0x54, 0x4f, 0x50, 0x50, 0x45, 0x44, 0x10, 0x03, 0x32, 0xf2, 0x06, 0x0a, 0x04, 0x42,
	0x6f, 0x73, 0x73, 0x12, 0x37, 0x0a, 0x04, 0x50, 0x69, 0x6e, 0x67, 0x12, 0x16, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x6f, 0x73, 0x73, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x6f, 0x73, 0x73,
	0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x55, 0x0a, 0x0e,
	0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x4d, 0x69, 0x6e, 0x69, 0x6f, 0x6e, 0x12, 0x20,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x6f, 0x73, 0x73, 0x52, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x65, 0x72, 0x4d, 0x69, 0x6e, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x21, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x6f, 0x73, 0x73, 0x52, 0x65, 0x67,
	0x69, 0x73, 0x74, 0x65, 0x72, 0x4d, 0x69, 0x6e, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x5b, 0x0a, 0x10, 0x55, 0x6e, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65,
	0x72, 0x4d, 0x69, 0x6e, 0x69, 0x6f, 0x6e, 0x12, 0x22, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x42, 0x6f, 0x73, 0x73, 0x55, 0x6e, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x4d, 0x69,
	0x6e, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x6f, 0x73, 0x73, 0x55, 0x6e, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74,
	0x65, 0x72, 0x4d, 0x69, 0x6e, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x52, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x4d, 0x69, 0x6e, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66,
	0x6f, 0x12, 0x1f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x6f, 0x73, 0x73, 0x47, 0x65,
	0x74, 0x4d, 0x69, 0x6e, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x20, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x6f, 0x73, 0x73, 0x47,
	0x65, 0x74, 0x4d, 0x69, 0x6e, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x49, 0x0a, 0x0a, 0x50, 0x72, 0x65, 0x70, 0x61, 0x72, 0x65, 0x4a,
	0x6f, 0x62, 0x12, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x6f, 0x73, 0x73, 0x50,
	0x72, 0x65, 0x70, 0x61, 0x72, 0x65, 0x4a, 0x6f, 0x62, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x6f, 0x73, 0x73, 0x50, 0x72, 0x65,
	0x70, 0x61, 0x72, 0x65, 0x4a, 0x6f, 0x62, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x3d, 0x0a, 0x06, 0x52, 0x75, 0x6e, 0x4a, 0x6f, 0x62, 0x12, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x42, 0x6f, 0x73, 0x73, 0x52, 0x75, 0x6e, 0x4a, 0x6f, 0x62, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x6f, 0x73, 0x73,
	0x52, 0x75, 0x6e, 0x4a, 0x6f, 0x62, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x43,
	0x0a, 0x08, 0x41, 0x62, 0x6f, 0x72, 0x74, 0x4a, 0x6f, 0x62, 0x12, 0x1a, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x42, 0x6f, 0x73, 0x73, 0x41, 0x62, 0x6f, 0x72, 0x74, 0x4a, 0x6f, 0x62, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x42,
	0x6f, 0x73, 0x73, 0x41, 0x62, 0x6f, 0x72, 0x74, 0x4a, 0x6f, 0x62, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x49, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x4a, 0x6f, 0x62, 0x49, 0x6e, 0x66,
	0x6f, 0x12, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x6f, 0x73, 0x73, 0x47, 0x65,
	0x74, 0x4a, 0x6f, 0x62, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x6f, 0x73, 0x73, 0x47, 0x65, 0x74, 0x4a,
	0x6f, 0x62, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x58,
	0x0a, 0x0f, 0x53, 0x74, 0x61, 0x72, 0x74, 0x45, 0x78, 0x70, 0x65, 0x72, 0x69, 0x6d, 0x65, 0x6e,
	0x74, 0x12, 0x21, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x6f, 0x73, 0x73, 0x53, 0x74,
	0x61, 0x72, 0x74, 0x45, 0x78, 0x70, 0x65, 0x72, 0x69, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x6f, 0x73,
	0x73, 0x53, 0x74, 0x61, 0x72, 0x74, 0x45, 0x78, 0x70, 0x65, 0x72, 0x69, 0x6d, 0x65, 0x6e, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x55, 0x0a, 0x0e, 0x53, 0x74, 0x6f, 0x70,
	0x45, 0x78, 0x70, 0x65, 0x72, 0x69, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x20, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x42, 0x6f, 0x73, 0x73, 0x53, 0x74, 0x6f, 0x70, 0x45, 0x78, 0x70, 0x65, 0x72,
	0x69, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x6f, 0x73, 0x73, 0x53, 0x74, 0x6f, 0x70, 0x45, 0x78, 0x70,
	0x65, 0x72, 0x69, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x5e, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x45, 0x78, 0x70, 0x65, 0x72, 0x69, 0x6d, 0x65, 0x6e, 0x74,
	0x49, 0x6e, 0x66, 0x6f, 0x12, 0x23, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x6f, 0x73,
	0x73, 0x47, 0x65, 0x74, 0x45, 0x78, 0x70, 0x65, 0x72, 0x69, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x42, 0x6f, 0x73, 0x73, 0x47, 0x65, 0x74, 0x45, 0x78, 0x70, 0x65, 0x72, 0x69, 0x6d,
	0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42,
	0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_diligent_boss_proto_rawDescOnce sync.Once
	file_diligent_boss_proto_rawDescData = file_diligent_boss_proto_rawDesc
)

func file_diligent_boss_proto_rawDescGZIP() []byte {
	file_diligent_boss_proto_rawDescOnce.Do(func() {
		file_diligent_boss_proto_rawDescData = protoimpl.X.CompressGZIP(file_diligent_boss_proto_rawDescData)
	})
	return file_diligent_boss_proto_rawDescData
}

var file_diligent_boss_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_diligent_boss_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_diligent_boss_proto_goTypes = []interface{}{
	(ExperimentState)(0),                  // 0: proto.ExperimentState
	(*BossPingRequest)(nil),               // 1: proto.BossPingRequest
	(*BossPingResponse)(nil),              // 2: proto.BossPingResponse
	(*BossRegisterMinionRequest)(nil),     // 3: proto.BossRegisterMinionRequest
	(*BossRegisterMinionResponse)(nil),    // 4: proto.BossRegisterMinionResponse
	(*BossUnregisterMinionRequest)(nil),   // 5: proto.BossUnregisterMinionRequest
	(*BossUnregisterMinionResponse)(nil),  // 6: proto.BossUnregisterMinionResponse
	(*MinionInfo)(nil),                    // 7: proto.MinionInfo
	(*MinionStatus)(nil),                  // 8: proto.MinionStatus
	(*BossGetMinionInfoRequest)(nil),      // 9: proto.BossGetMinionInfoRequest
	(*BossGetMinionInfoResponse)(nil),     // 10: proto.BossGetMinionInfoResponse
	(*BossPrepareJobRequest)(nil),         // 11: proto.BossPrepareJobRequest
	(*BossPrepareJobResponse)(nil),        // 12: proto.BossPrepareJobResponse
	(*BossRunJobRequest)(nil),             // 13: proto.BossRunJobRequest
	(*BossRunJobResponse)(nil),            // 14: proto.BossRunJobResponse
	(*BossAbortJobRequest)(nil),           // 15: proto.BossAbortJobRequest
	(*BossAbortJobResponse)(nil),          // 16: proto.BossAbortJobResponse
	(*BossJobInfo)(nil),                   // 17: proto.BossJobInfo
	(*BossGetJobInfoRequest)(nil),         // 18: proto.BossGetJobInfoRequest
	(*BossGetJobInfoResponse)(nil),        // 19: proto.BossGetJobInfoResponse
	(*ExperimentInfo)(nil),                // 20: proto.ExperimentInfo
	(*BossStartExperimentRequest)(nil),    // 21: proto.BossStartExperimentRequest
	(*BossStartExperimentResponse)(nil),   // 22: proto.BossStartExperimentResponse
	(*BossStopExperimentRequest)(nil),     // 23: proto.BossStopExperimentRequest
	(*BossStopExperimentResponse)(nil),    // 24: proto.BossStopExperimentResponse
	(*BossGetExperimentInfoRequest)(nil),  // 25: proto.BossGetExperimentInfoRequest
	(*BossGetExperimentInfoResponse)(nil), // 26: proto.BossGetExperimentInfoResponse
	(*BuildInfo)(nil),                     // 27: proto.BuildInfo
	(*ProcessInfo)(nil),                   // 28: proto.ProcessInfo
	(*GeneralStatus)(nil),                 // 29: proto.GeneralStatus
	(*MinionJobInfo)(nil),                 // 30: proto.MinionJobInfo
	(*JobSpec)(nil),                       // 31: proto.JobSpec
	(JobState)(0),                         // 32: proto.JobState
}
var file_diligent_boss_proto_depIdxs = []int32{
	27, // 0: proto.BossPingResponse.build_info:type_name -> proto.BuildInfo
	28, // 1: proto.BossPingResponse.process_info:type_name -> proto.ProcessInfo
	29, // 2: proto.BossRegisterMinionResponse.status:type_name -> proto.GeneralStatus
	29, // 3: proto.BossUnregisterMinionResponse.status:type_name -> proto.GeneralStatus
	29, // 4: proto.MinionInfo.reachability:type_name -> proto.GeneralStatus
	27, // 5: proto.MinionInfo.build_info:type_name -> proto.BuildInfo
	28, // 6: proto.MinionInfo.process_info:type_name -> proto.ProcessInfo
	30, // 7: proto.MinionInfo.job_info:type_name -> proto.MinionJobInfo
	29, // 8: proto.MinionStatus.status:type_name -> proto.GeneralStatus
	7,  // 9: proto.BossGetMinionInfoResponse.minion_infos:type_name -> proto.MinionInfo
	31, // 10: proto.BossPrepareJobRequest.job_spec:type_name -> proto.JobSpec
	29, // 11: proto.BossPrepareJobResponse.status:type_name -> proto.GeneralStatus
	8,  // 12: proto.BossPrepareJobResponse.minion_statuses:type_name -> proto.MinionStatus
	29, // 13: proto.BossRunJobResponse.status:type_name -> proto.GeneralStatus
	8,  // 14: proto.BossRunJobResponse.minion_statuses:type_name -> proto.MinionStatus
	29, // 15: proto.BossAbortJobResponse.status:type_name -> proto.GeneralStatus
	8,  // 16: proto.BossAbortJobResponse.minion_statuses:type_name -> proto.MinionStatus
	31, // 17: proto.BossJobInfo.job_spec:type_name -> proto.JobSpec
	32, // 18: proto.BossJobInfo.job_state:type_name -> proto.JobState
	29, // 19: proto.BossGetJobInfoResponse.status:type_name -> proto.GeneralStatus
	17, // 20: proto.BossGetJobInfoResponse.job_info:type_name -> proto.BossJobInfo
	0,  // 21: proto.ExperimentInfo.state:type_name -> proto.ExperimentState
	29, // 22: proto.BossStartExperimentResponse.status:type_name -> proto.GeneralStatus
	29, // 23: proto.BossStopExperimentResponse.status:type_name -> proto.GeneralStatus
	29, // 24: proto.BossGetExperimentInfoResponse.status:type_name -> proto.GeneralStatus
	20, // 25: proto.BossGetExperimentInfoResponse.experiment_info:type_name -> proto.ExperimentInfo
	1,  // 26: proto.Boss.Ping:input_type -> proto.BossPingRequest
	3,  // 27: proto.Boss.RegisterMinion:input_type -> proto.BossRegisterMinionRequest
	5,  // 28: proto.Boss.UnregisterMinion:input_type -> proto.BossUnregisterMinionRequest
	9,  // 29: proto.Boss.GetMinionInfo:input_type -> proto.BossGetMinionInfoRequest
	11, // 30: proto.Boss.PrepareJob:input_type -> proto.BossPrepareJobRequest
	13, // 31: proto.Boss.RunJob:input_type -> proto.BossRunJobRequest
	15, // 32: proto.Boss.AbortJob:input_type -> proto.BossAbortJobRequest
	18, // 33: proto.Boss.GetJobInfo:input_type -> proto.BossGetJobInfoRequest
	21, // 34: proto.Boss.StartExperiment:input_type -> proto.BossStartExperimentRequest
	23, // 35: proto.Boss.StopExperiment:input_type -> proto.BossStopExperimentRequest
	25, // 36: proto.Boss.GetExperimentInfo:input_type -> proto.BossGetExperimentInfoRequest
	2,  // 37: proto.Boss.Ping:output_type -> proto.BossPingResponse
	4,  // 38: proto.Boss.RegisterMinion:output_type -> proto.BossRegisterMinionResponse
	6,  // 39: proto.Boss.UnregisterMinion:output_type -> proto.BossUnregisterMinionResponse
	10, // 40: proto.Boss.GetMinionInfo:output_type -> proto.BossGetMinionInfoResponse
	12, // 41: proto.Boss.PrepareJob:output_type -> proto.BossPrepareJobResponse
	14, // 42: proto.Boss.RunJob:output_type -> proto.BossRunJobResponse
	16, // 43: proto.Boss.AbortJob:output_type -> proto.BossAbortJobResponse
	19, // 44: proto.Boss.GetJobInfo:output_type -> proto.BossGetJobInfoResponse
	22, // 45: proto.Boss.StartExperiment:output_type -> proto.BossStartExperimentResponse
	24, // 46: proto.Boss.StopExperiment:output_type -> proto.BossStopExperimentResponse
	26, // 47: proto.Boss.GetExperimentInfo:output_type -> proto.BossGetExperimentInfoResponse
	37, // [37:48] is the sub-list for method output_type
	26, // [26:37] is the sub-list for method input_type
	26, // [26:26] is the sub-list for extension type_name
	26, // [26:26] is the sub-list for extension extendee
	0,  // [0:26] is the sub-list for field type_name
}

func init() { file_diligent_boss_proto_init() }
func file_diligent_boss_proto_init() {
	if File_diligent_boss_proto != nil {
		return
	}
	file_diligent_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_diligent_boss_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BossPingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_diligent_boss_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BossPingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_diligent_boss_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BossRegisterMinionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_diligent_boss_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BossRegisterMinionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_diligent_boss_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BossUnregisterMinionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_diligent_boss_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BossUnregisterMinionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_diligent_boss_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MinionInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_diligent_boss_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MinionStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_diligent_boss_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BossGetMinionInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_diligent_boss_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BossGetMinionInfoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_diligent_boss_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BossPrepareJobRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_diligent_boss_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BossPrepareJobResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_diligent_boss_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BossRunJobRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_diligent_boss_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BossRunJobResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_diligent_boss_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BossAbortJobRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_diligent_boss_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BossAbortJobResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_diligent_boss_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BossJobInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_diligent_boss_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BossGetJobInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_diligent_boss_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BossGetJobInfoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_diligent_boss_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExperimentInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_diligent_boss_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BossStartExperimentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_diligent_boss_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BossStartExperimentResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_diligent_boss_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BossStopExperimentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_diligent_boss_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BossStopExperimentResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_diligent_boss_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BossGetExperimentInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_diligent_boss_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BossGetExperimentInfoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_diligent_boss_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_diligent_boss_proto_goTypes,
		DependencyIndexes: file_diligent_boss_proto_depIdxs,
		EnumInfos:         file_diligent_boss_proto_enumTypes,
		MessageInfos:      file_diligent_boss_proto_msgTypes,
	}.Build()
	File_diligent_boss_proto = out.File
	file_diligent_boss_proto_rawDesc = nil
	file_diligent_boss_proto_goTypes = nil
	file_diligent_boss_proto_depIdxs = nil
}
